CREATE TABLE `booking_transactions` (
  `id` text PRIMARY KEY NOT NULL,
  `tenant_id` text NOT NULL,
  `company_id` text NOT NULL,
  `import_id` text NOT NULL,
  `import_year` integer NOT NULL,
  `import_month` integer NOT NULL,
  `business_week` integer,
  `booking_date` text NOT NULL,
  `booking_no` text NOT NULL,
  `booking_number` text,
  `branch` text NOT NULL,
  `customer` text NOT NULL,
  `product` text NOT NULL,
  `status` text NOT NULL,
  `booking_year` integer,
  `booking_month` integer,
  `branch_code` text,
  `branch_name` text,
  `salesperson_code` text,
  `salesperson_name` text,
  `product_type` text,
  `product_model` text,
  `customer_name` text,
  `booking_price` text,
  `deposit_amount` text,
  `booking_status` text,
  `purchase_status` text,
  `created_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL,
  `created_by` text NOT NULL
);
