CREATE TABLE `stock_transactions` (
  `id` text PRIMARY KEY NOT NULL,
  `tenant_id` text NOT NULL,
  `company_id` text NOT NULL,
  `import_id` text NOT NULL,
  `import_year` integer NOT NULL,
  `import_month` integer NOT NULL,
  `business_week` integer,
  `as_of_date` text NOT NULL,
  `branch` text NOT NULL,
  `product` text NOT NULL,
  `quantity` integer NOT NULL,
  `stock_date` text,
  `branch_code` text,
  `branch_name` text,
  `product_type` text,
  `product_group` text,
  `product_model` text,
  `kmm_flag` integer,
  `msrp` text,
  `stock_status` text,
  `stock_number` text,
  `serial_number` text,
  `engine_number` text,
  `chassis_number` text,
  `stock_age_days` integer,
  `snapshot_date` text,
  `created_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL,
  `created_by` text NOT NULL
);
