-- KAI Phase 1E seed.
-- The referenced workbook is not present in the checked-out workspace. This
-- seed is reconstructed from the latest Phase 1E task specification and the
-- verified KMM D1 schema documented in docs/kai/KAI_PHASE1_VALIDATION.md.

INSERT OR IGNORE INTO `kai_metrics`
	(`metric_code`, `metric_name`, `description`, `formula`, `data_source`, `unit_type`, `business_rule`, `ai_usage`)
VALUES
	('SALES001', 'Sales Unit', 'จำนวนเครื่องขายจริงตามกฎ Sales Unit ของ KMM', 'SUM(quantity) ในรายการที่ product_type เป็น TT, CH, EX หรือ TP', 'OPERATIONS_DB.sales_transactions.quantity, product_type, sale_date', 'Unit', 'นับเฉพาะ TT, CH, EX, TP; ไม่รวม IM, IMO, OT', 'ตอบยอดขายเป็นจำนวนคันและใช้จัดอันดับสาขา รุ่น และช่วงเวลา'),
	('SALES002', 'Sales Value', 'มูลค่ายอดขายตามค่า Final Received ที่ระบบใช้อยู่', 'SUM(CAST(final_received AS REAL)) ของรายการขายที่ valid ในขอบเขต', 'OPERATIONS_DB.sales_transactions.final_received', 'Value', 'ใช้ final_received เป็นค่า Sales Value ปัจจุบัน; sale_amount เป็น raw source อีกฟิลด์หนึ่ง', 'ตอบมูลค่ายอดขายและใช้เปรียบเทียบช่วงเวลา'),
	('SALES003', 'GP Value', 'กำไรขั้นต้นจากฟิลด์ GP1 ที่มีอยู่จริง', 'SUM(CAST(gp1 AS REAL)) เมื่อทุกแถวในขอบเขตมีค่า GP1', 'OPERATIONS_DB.sales_transactions.gp1', 'Value', 'ถ้า GP1 ไม่ครบ ให้รายงานว่าไม่พร้อมใช้แทนการเติมค่าประมาณ', 'ตอบกำไรขั้นต้นและตรวจความพร้อมของข้อมูล'),
	('SALES004', 'Achievement %', 'สัดส่วนผลงานจริงเทียบ Target ที่อนุมัติ', 'Actual / Target * 100', 'OPERATIONS_DB.sales_transactions + business_targets.target_value', '%', 'ใช้ได้เมื่อมี Target ของบริษัทและ metric ตรงกัน; ห้ามสร้าง Target เอง', 'ตอบเปอร์เซ็นต์ทำได้เทียบเป้าหมาย'),
	('SALES005', 'Growth %', 'การเติบโตของ metric ระหว่างสองช่วงที่เทียบกัน', '(Current - Comparison) / Comparison * 100', 'OPERATIONS_DB.sales_transactions.sale_date และ metric ที่เลือก', '%', 'ถ้าค่า Comparison เป็นศูนย์หรือไม่มีข้อมูล ให้รายงาน N/A', 'ตอบการเพิ่มหรือลดเทียบเดือนหรือปีที่ผู้ใช้ระบุ'),
	('SALES006', 'Sales Gap', 'ส่วนต่างระหว่าง Target กับ Actual ในหน่วยขาย', 'Target - Actual', 'OPERATIONS_DB.business_targets.target_value + sales_transactions.quantity', 'Unit', 'เป็น Gap ของ Sales Units; ต้องมี Target ที่อนุมัติและใช้ขอบเขตเดียวกัน', 'ตอบจำนวนคันที่ขาดหรือเกินเป้าหมาย'),
	('BOOK001', 'Booking Unit', 'จำนวนรายการ Booking ที่อยู่ในขอบเขตคำถาม', 'COUNT(*) ของ booking_transactions หลังใช้ตัวกรองบริษัทและช่วงเวลา', 'OPERATIONS_DB.booking_transactions.booking_date, booking_no, company_id', 'Unit', 'เป็นจำนวนแถว Booking; การยืนยันว่า 1 แถวเท่ากับ 1 คันต้องอิง source contract', 'ตอบจำนวน Booking ปัจจุบันและเปรียบเทียบช่วงเวลา'),
	('BOOK002', 'Booking Value', 'มูลค่าจองจากราคา Booking ที่บันทึกไว้', 'SUM(CAST(booking_price AS REAL))', 'OPERATIONS_DB.booking_transactions.booking_price', 'Value', 'ไม่ประมาณราคาจากฟิลด์อื่น; ค่าว่างต้องไม่ถูกนับเป็นศูนย์โดยอัตโนมัติ', 'ตอบมูลค่า Booking และจัดอันดับตามมูลค่า'),
	('BOOK003', 'Booking Aging', 'อายุของ Booking จากวันที่จองถึงวันที่อ้างอิง', 'Reference Date - booking_date', 'OPERATIONS_DB.booking_transactions.booking_date', 'Day', '>90 วัน = Aging Risk ตาม Phase 1E rule', 'ตอบจำนวนและรายการ Booking ที่ต้องติดตาม'),
	('BOOK004', 'Booking Conversion', 'สัดส่วนรายการ Booking ที่มี status เป็น Delivered', 'COUNT(status = Delivered) / COUNT(*) * 100', 'OPERATIONS_DB.booking_transactions.status, booking_status, purchase_status', '%', 'ใช้สถานะที่ adapter อนุมัติ; ห้ามสร้าง lifecycle status ใหม่', 'ตอบอัตราเปลี่ยน Booking เป็นการขายหรือส่งมอบ'),
	('STOCK001', 'Stock Unit', 'จำนวนเครื่อง Stock ปัจจุบันตาม canonical current-stock rule', 'COUNT(*) ของ Free Stock หลังใช้ company ownership และ physical-id deduplication', 'OPERATIONS_DB.stock_transactions.stock_status, kmm_flag, stock_number, serial_number, engine_number, chassis_number', 'Unit', 'ใช้ current Free Stock rule; ไม่ใช้แถวซ้ำเป็นหลายคัน', 'ตอบ Stock ปัจจุบันและแยกตามรุ่นหรือสาขา'),
	('STOCK002', 'Stock Value', 'มูลค่า Stock จาก MSRP ที่บันทึกไว้', 'SUM(CAST(msrp AS REAL)) ของ current stock ที่มี MSRP', 'OPERATIONS_DB.stock_transactions.msrp, stock_status', 'Value', 'ไม่เติม MSRP ที่หายไปและต้องรักษา current-stock scope', 'ตอบมูลค่า Stock และจัดอันดับมูลค่าค้าง'),
	('STOCK003', 'Stock Aging', 'อายุ Stock ตามฟิลด์ Stock Age ที่นำเข้าไว้', 'stock_age_days', 'OPERATIONS_DB.stock_transactions.stock_age_days, stock_date, as_of_date', 'Day', '>90 วัน = Aging Stock ตาม Phase 1E rule', 'ตอบจำนวน Stock เกิน 90 วันและรุ่นที่เกี่ยวข้อง'),
	('STOCK004', 'Slow Moving', 'Stock ที่มีอายุค้างระดับ Slow Moving', 'stock_age_days > 180', 'OPERATIONS_DB.stock_transactions.stock_age_days', 'Unit', '>180 วัน = Slow Moving; ต้องใช้ current-stock scope ก่อนจัดกลุ่ม', 'ตอบรายการและรุ่นที่มีความเสี่ยงค้างนาน');
--> statement-breakpoint

INSERT OR IGNORE INTO `kai_data_dictionary`
	(`business_name`, `table_name`, `field_name`, `data_type`, `description`, `domain`)
VALUES
	('Company Scope', 'sales_transactions', 'company_id', 'TEXT', 'ขอบเขตบริษัทของข้อมูล Sales ใน OPERATIONS_DB', 'sales'),
	('Sales Import Year', 'sales_transactions', 'import_year', 'INTEGER', 'ปีของงวดนำเข้า Sales', 'sales'),
	('Sales Import Month', 'sales_transactions', 'import_month', 'INTEGER', 'เดือนของงวดนำเข้า Sales', 'sales'),
	('Sales Date', 'sales_transactions', 'sale_date', 'TEXT', 'วันที่ขายจริงตาม canonical Sales row', 'sales'),
	('Sales Invoice', 'sales_transactions', 'invoice_no', 'TEXT', 'เลขที่ใบขาย', 'sales'),
	('Sales Branch', 'sales_transactions', 'branch', 'TEXT', 'สาขาที่อยู่ในรายการ Sales', 'sales'),
	('Sales Model Code', 'sales_transactions', 'model_code', 'TEXT', 'รหัสรุ่นจากรายการ Sales', 'sales'),
	('Sales Model', 'sales_transactions', 'model', 'TEXT', 'ชื่อรุ่นจากรายการ Sales', 'sales'),
	('Sales Quantity', 'sales_transactions', 'quantity', 'INTEGER', 'จำนวนหน่วยใน Sales row', 'sales'),
	('Sales Raw Amount', 'sales_transactions', 'sale_amount', 'TEXT', 'มูลค่า Sale Amount ที่นำเข้า; ไม่ใช่ canonical Sales Value ปัจจุบัน', 'sales'),
	('Sales Value Source', 'sales_transactions', 'final_received', 'TEXT', 'ค่า Final Received ที่ business service ใช้เป็น Sales Value', 'sales'),
	('Sales GP Source', 'sales_transactions', 'gp1', 'TEXT', 'ค่า GP1 ที่ใช้เป็นแหล่ง Gross Profit เมื่อข้อมูลครบ', 'sales'),
	('Sales Product Type', 'sales_transactions', 'product_type', 'TEXT', 'รหัสกลุ่มสินค้า เช่น 01-TT, 02-CH, 03-TP, 04-EX, 06-IM, 07-IMO, 08-OT', 'sales'),
	('Sales Person Code', 'sales_transactions', 'salesperson_code', 'TEXT', 'รหัสพนักงานขาย', 'sales'),
	('Sales Person Name', 'sales_transactions', 'salesperson_name', 'TEXT', 'ชื่อพนักงานขาย', 'sales'),
	('Booking Company Scope', 'booking_transactions', 'company_id', 'TEXT', 'ขอบเขตบริษัทของข้อมูล Booking ใน OPERATIONS_DB', 'booking'),
	('Booking Date', 'booking_transactions', 'booking_date', 'TEXT', 'วันที่จอง ใช้คำนวณ Booking Aging', 'booking'),
	('Booking Number', 'booking_transactions', 'booking_no', 'TEXT', 'เลขที่ Booking หลัก', 'booking'),
	('Booking Number Canonical', 'booking_transactions', 'booking_number', 'TEXT', 'เลขที่ Booking ที่ adapter รองรับเพิ่มเติม', 'booking'),
	('Booking Branch', 'booking_transactions', 'branch', 'TEXT', 'สาขาจากรายการ Booking', 'booking'),
	('Booking Branch Code', 'booking_transactions', 'branch_code', 'TEXT', 'รหัสสาขาจากรายการ Booking', 'booking'),
	('Booking Branch Name', 'booking_transactions', 'branch_name', 'TEXT', 'ชื่อสาขาจากรายการ Booking', 'booking'),
	('Booking Customer', 'booking_transactions', 'customer_name', 'TEXT', 'ชื่อลูกค้าจากรายการ Booking', 'booking'),
	('Booking Product Type', 'booking_transactions', 'product_type', 'TEXT', 'กลุ่มสินค้าจากรายการ Booking', 'booking'),
	('Booking Product Model', 'booking_transactions', 'product_model', 'TEXT', 'รุ่นสินค้าจากรายการ Booking', 'booking'),
	('Booking Value Source', 'booking_transactions', 'booking_price', 'TEXT', 'ราคาจองที่ใช้เป็น Booking Value', 'booking'),
	('Booking Deposit', 'booking_transactions', 'deposit_amount', 'TEXT', 'เงินมัดจำที่บันทึกไว้', 'booking'),
	('Booking Status', 'booking_transactions', 'status', 'TEXT', 'สถานะ canonical ที่ adapter ใช้ตรวจ Delivered', 'booking'),
	('Booking Status Detail', 'booking_transactions', 'booking_status', 'TEXT', 'สถานะ Booking จาก source', 'booking'),
	('Booking Purchase Status', 'booking_transactions', 'purchase_status', 'TEXT', 'สถานะการซื้อจาก source', 'booking'),
	('Stock Company Scope', 'stock_transactions', 'company_id', 'TEXT', 'ขอบเขตบริษัทของข้อมูล Stock ใน OPERATIONS_DB', 'stock'),
	('Stock Snapshot Date', 'stock_transactions', 'as_of_date', 'TEXT', 'วันที่อ้างอิง snapshot Stock', 'stock'),
	('Stock Date', 'stock_transactions', 'stock_date', 'TEXT', 'วันที่ Stock จาก source', 'stock'),
	('Stock Branch', 'stock_transactions', 'branch', 'TEXT', 'สาขาของ Stock row', 'stock'),
	('Stock Branch Code', 'stock_transactions', 'branch_code', 'TEXT', 'รหัสสาขาของ Stock row', 'stock'),
	('Stock Branch Name', 'stock_transactions', 'branch_name', 'TEXT', 'ชื่อสาขาของ Stock row', 'stock'),
	('Stock Product Type', 'stock_transactions', 'product_type', 'TEXT', 'กลุ่มสินค้าจาก source Stock', 'stock'),
	('Stock Product Group', 'stock_transactions', 'product_group', 'TEXT', 'กลุ่มสินค้าที่ผ่าน mapping ของ Stock', 'stock'),
	('Stock Product Model', 'stock_transactions', 'product_model', 'TEXT', 'รุ่นสินค้าจาก source Stock', 'stock'),
	('Stock Quantity', 'stock_transactions', 'quantity', 'INTEGER', 'จำนวนที่นำเข้าใน Stock row; canonical dashboard นับ physical rows', 'stock'),
	('Stock Value Source', 'stock_transactions', 'msrp', 'TEXT', 'MSRP ที่ใช้คำนวณ Stock Value', 'stock'),
	('Stock Status', 'stock_transactions', 'stock_status', 'TEXT', 'สถานะ Stock; current rule ใช้ Free Stock', 'stock'),
	('KMM Ownership Flag', 'stock_transactions', 'kmm_flag', 'INTEGER', 'ธง ownership ของ KMM ตาม source contract', 'stock'),
	('Stock Age Days', 'stock_transactions', 'stock_age_days', 'INTEGER', 'อายุ Stock ที่ source นำเข้าไว้', 'stock'),
	('Stock Number', 'stock_transactions', 'stock_number', 'TEXT', 'รหัส Stock', 'stock'),
	('Serial Number', 'stock_transactions', 'serial_number', 'TEXT', 'หมายเลข Serial สำหรับ deduplication', 'stock'),
	('Engine Number', 'stock_transactions', 'engine_number', 'TEXT', 'หมายเลขเครื่องยนต์สำหรับ deduplication', 'stock'),
	('Chassis Number', 'stock_transactions', 'chassis_number', 'TEXT', 'หมายเลขตัวถังสำหรับ deduplication', 'stock'),
	('Branch Master', 'branches', 'branch_code', 'TEXT', 'รหัส Branch Master ที่ยืนยันใน COMPANY_DB; ไม่ใช่ OPERATIONS_DB', 'organization'),
	('Branch Master Name', 'branches', 'branch_name', 'TEXT', 'ชื่อสาขาใน COMPANY_DB', 'organization'),
	('Branch Region', 'branches', 'region', 'TEXT', 'ภาคหรือเขตใน COMPANY_DB', 'organization'),
	('Branch Township', 'branches', 'township', 'TEXT', 'พื้นที่ Township ใน COMPANY_DB', 'organization'),
	('Branch Company Scope', 'branches', 'company_id', 'TEXT', 'ขอบเขตบริษัทของ Branch Master ใน COMPANY_DB', 'organization'),
	('Product Type Classification (application mapping)', 'APPLICATION_MAPPING', 'lib/sales/business-service.ts::SALES_PRODUCT_TYPE_GROUPS', 'CODE_RULE', 'ไม่พบตาราง product หรือ product_master ใน schema จริง; ใช้ mapping ใน application และห้าม query เป็น table', 'product'),
	('Stock Product Classification (application mapping)', 'APPLICATION_MAPPING', 'lib/dashboard/stock-selectors.ts::aliases', 'CODE_RULE', 'Stock product aliases และ current-stock rule อยู่ใน application mapping ที่ตรวจสอบแล้ว', 'product');
--> statement-breakpoint

INSERT OR IGNORE INTO `kai_question_library`
	(`question`, `intent`, `domain`, `required_metric`, `response_type`)
VALUES
	('ยอดขายเดือนนี้เท่าไหร่', 'SALES_CURRENT', 'sales', 'SALES001,SALES002', 'summary'),
	('เดือนนี้ขายได้กี่คัน', 'SALES_CURRENT', 'sales', 'SALES001', 'summary'),
	('ยอดขายเดือนนี้เป็นเงินเท่าไหร่', 'SALES_VALUE_CURRENT', 'sales', 'SALES002', 'summary'),
	('ยอดขายเดือนนี้เทียบเดือนที่แล้ว', 'SALES_MONTH_COMPARE', 'sales', 'SALES001,SALES002,SALES005', 'comparison'),
	('ยอดขายเดือนนี้เทียบเดือนเดียวกันปีที่แล้ว', 'SALES_YOY_COMPARE', 'sales', 'SALES001,SALES002,SALES005', 'comparison'),
	('ยอดขายเดือน 5 ปี 2023 เท่าไหร่', 'SALES_HISTORY_QUERY', 'sales', 'SALES001,SALES002', 'summary'),
	('ยอดขายเดือน 5 ปี 2023 เทียบปีนี้เป็นอย่างไร', 'SALES_YOY_COMPARE', 'sales', 'SALES001,SALES002,SALES005', 'comparison'),
	('สาขาไหนขายดีที่สุด', 'SALES_BRANCH_RANKING', 'sales', 'SALES001', 'ranking'),
	('รุ่นไหนขายดีที่สุด', 'SALES_MODEL_RANKING', 'sales', 'SALES001', 'ranking'),
	('Product Type ไหนขายดีที่สุด', 'SALES_PRODUCT_RANKING', 'sales', 'SALES001', 'ranking'),
	('GP เดือนนี้เท่าไหร่', 'SALES_GP_QUERY', 'sales', 'SALES003', 'summary'),
	('ยอดขายได้กี่เปอร์เซ็นต์ของเป้า', 'SALES_ACHIEVEMENT_QUERY', 'sales', 'SALES004', 'summary'),
	('ยอดขายขาดเป้าเท่าไหร่', 'SALES_GAP_QUERY', 'sales', 'SALES006', 'summary'),
	('ยอดขายโตขึ้นกี่เปอร์เซ็นต์จากปีที่แล้ว', 'SALES_GROWTH_QUERY', 'sales', 'SALES005', 'summary'),
	('เดือนนี้จองเท่าไหร่', 'BOOKING_CURRENT', 'booking', 'BOOK001', 'summary'),
	('เดือนนี้มี Booking กี่รายการ', 'BOOKING_CURRENT', 'booking', 'BOOK001', 'summary'),
	('Booking เดือนนี้มูลค่าเท่าไหร่', 'BOOKING_VALUE_CURRENT', 'booking', 'BOOK002', 'summary'),
	('Booking เทียบเดือนที่แล้ว', 'BOOKING_MONTH_COMPARE', 'booking', 'BOOK001,BOOK002', 'comparison'),
	('Booking เดือนนี้เทียบปีที่แล้ว', 'BOOKING_YOY_COMPARE', 'booking', 'BOOK001,BOOK002', 'comparison'),
	('Booking เดือน 5 ปี 2023 เท่าไหร่', 'BOOKING_HISTORY_QUERY', 'booking', 'BOOK001,BOOK002', 'summary'),
	('Booking อายุเกิน 90 วันมีเท่าไหร่', 'BOOKING_AGING_QUERY', 'booking', 'BOOK003', 'summary'),
	('Booking เกิน 90 วันมีรายการอะไรบ้าง', 'BOOKING_AGING_LIST', 'booking', 'BOOK003', 'list'),
	('รุ่นไหนมี Booking มากที่สุด', 'BOOKING_MODEL_RANKING', 'booking', 'BOOK001', 'ranking'),
	('สาขาไหนมี Booking มากที่สุด', 'BOOKING_BRANCH_RANKING', 'booking', 'BOOK001', 'ranking'),
	('Booking Conversion เดือนนี้เท่าไหร่', 'BOOKING_CONVERSION_QUERY', 'booking', 'BOOK004', 'summary'),
	('Stock ปัจจุบันมีกี่คัน', 'STOCK_CURRENT', 'stock', 'STOCK001', 'summary'),
	('Stock ปัจจุบันมูลค่าเท่าไหร่', 'STOCK_VALUE_CURRENT', 'stock', 'STOCK002', 'summary'),
	('Stock เกิน 90 วันมีกี่คัน', 'STOCK_AGING_QUERY', 'stock', 'STOCK003', 'summary'),
	('Stock เกิน 90 วันมีรุ่นอะไรบ้าง', 'STOCK_AGING_MODEL_RANKING', 'stock', 'STOCK003', 'ranking'),
	('รุ่นไหน Stock ค้างมากที่สุด', 'STOCK_MODEL_RANKING', 'stock', 'STOCK001,STOCK003', 'ranking'),
	('สาขาไหนมี Stock ค้างมากที่สุด', 'STOCK_BRANCH_RANKING', 'stock', 'STOCK001,STOCK003', 'ranking'),
	('Stock อายุเกิน 180 วันมีเท่าไหร่', 'STOCK_SLOW_MOVING_QUERY', 'stock', 'STOCK004', 'summary'),
	('Stock Slow Moving มีรุ่นอะไรบ้าง', 'STOCK_SLOW_MOVING_MODEL_RANKING', 'stock', 'STOCK004', 'ranking'),
	('Stock รุ่น DC70G PRO มีเท่าไหร่', 'STOCK_MODEL_QUERY', 'stock', 'STOCK001', 'summary');
--> statement-breakpoint

INSERT OR IGNORE INTO `kai_query_templates`
	(`intent`, `purpose`, `required_data`, `query_logic`)
VALUES
	('SALES_CURRENT', 'ยอดขาย Sales ในช่วงวันที่กำหนด', 'sales_transactions.company_id, sale_date, product_type, quantity', 'SELECT SUM(quantity) AS sales_unit FROM sales_transactions WHERE company_id = :company_id AND sale_date >= :start_date AND sale_date < :end_date AND normalized product_type IN (TT, CH, EX, TP)'),
	('SALES_VALUE_CURRENT', 'มูลค่า Sales ในช่วงวันที่กำหนด', 'sales_transactions.company_id, sale_date, final_received', 'SELECT SUM(CAST(final_received AS REAL)) AS sales_value FROM sales_transactions WHERE company_id = :company_id AND sale_date >= :start_date AND sale_date < :end_date AND final_received IS NOT NULL'),
	('SALES_MONTH_COMPARE', 'เปรียบเทียบ Sales ระหว่างเดือนปัจจุบันและเดือนก่อน', 'sales_transactions.sale_date, quantity, final_received', 'Run SALES001 and SALES002 for :current_start/:current_end and :previous_start/:previous_end; calculate difference and Growth % outside SQL'),
	('SALES_YOY_COMPARE', 'เปรียบเทียบเดือนเดียวกันคนละปี', 'sales_transactions.sale_date, quantity, final_received', 'Run SALES001 and SALES002 for :current_year/:month and :comparison_year/:month; keep both periods explicit'),
	('SALES_HISTORY_QUERY', 'ตอบยอด Sales ของเดือนและปีที่ระบุ', 'sales_transactions.sale_date, quantity, final_received', 'WHERE company_id = :company_id AND strftime(''%Y'', sale_date) = :year AND strftime(''%m'', sale_date) = printf(''%02d'', :month)'),
	('SALES_BRANCH_RANKING', 'จัดอันดับสาขาตาม Sales Unit', 'sales_transactions.branch, product_type, quantity', 'Apply SALES001 scope, GROUP BY branch, ORDER BY sales_unit DESC'),
	('SALES_MODEL_RANKING', 'จัดอันดับรุ่นตาม Sales Unit', 'sales_transactions.model, product_type, quantity', 'Apply SALES001 scope, GROUP BY model, ORDER BY sales_unit DESC'),
	('SALES_PRODUCT_RANKING', 'จัดอันดับ Product Type ตาม Sales Unit', 'sales_transactions.product_type, quantity', 'Apply SALES001 scope, GROUP BY product_type, ORDER BY sales_unit DESC'),
	('SALES_GP_QUERY', 'ตอบ GP1 ตามช่วงเวลา', 'sales_transactions.gp1, sale_date', 'SUM(CAST(gp1 AS REAL)) only when every scoped row has a non-null GP1; otherwise return unavailable'),
	('SALES_ACHIEVEMENT_QUERY', 'เทียบ Sales Unit กับ Target ที่อนุมัติ', 'business_targets.target_value, sales_transactions.quantity', 'Load approved SALES_UNITS target for exact company/year/month scope; divide actual by target and return unavailable when target is absent'),
	('SALES_GAP_QUERY', 'คำนวณจำนวนคันที่ขาดหรือเกิน Target', 'business_targets.target_value, sales_transactions.quantity', 'SALES_UNITS target - SALES001 actual for the exact same scope'),
	('SALES_GROWTH_QUERY', 'คำนวณ Growth ระหว่างสองผลลัพธ์', 'current_value, comparison_value', '(current_value - comparison_value) / comparison_value * 100; return N/A when comparison_value is zero or missing'),
	('BOOKING_CURRENT', 'ยอด Booking ในช่วงเวลา', 'booking_transactions.company_id, booking_date, booking_no', 'SELECT COUNT(*) AS booking_unit FROM booking_transactions WHERE company_id = :company_id AND booking_date >= :start_date AND booking_date < :end_date'),
	('BOOKING_VALUE_CURRENT', 'มูลค่า Booking ในช่วงเวลา', 'booking_transactions.booking_date, booking_price', 'SELECT SUM(CAST(booking_price AS REAL)) AS booking_value FROM booking_transactions WHERE company_id = :company_id AND booking_date >= :start_date AND booking_date < :end_date AND booking_price IS NOT NULL'),
	('BOOKING_MONTH_COMPARE', 'เปรียบเทียบ Booking ระหว่างสองเดือน', 'booking_date, booking_no, booking_price', 'Run BOOKING_CURRENT and BOOKING_VALUE_CURRENT for both explicit date ranges; calculate difference outside SQL'),
	('BOOKING_YOY_COMPARE', 'เปรียบเทียบ Booking เดือนเดียวกันคนละปี', 'booking_date, booking_no, booking_price', 'Run BOOKING_CURRENT and BOOKING_VALUE_CURRENT for :year/:month and :comparison_year/:month'),
	('BOOKING_HISTORY_QUERY', 'ตอบ Booking ของเดือนและปีที่ระบุ', 'booking_date, booking_no, booking_price', 'WHERE company_id = :company_id AND strftime(''%Y'', booking_date) = :year AND strftime(''%m'', booking_date) = printf(''%02d'', :month)'),
	('BOOKING_AGING_QUERY', 'นับ Booking อายุเกิน 90 วัน', 'booking_date, booking_status, status', 'WHERE company_id = :company_id AND julianday(:reference_date) - julianday(booking_date) > 90 AND status NOT IN (:closed_statuses)'),
	('BOOKING_AGING_LIST', 'แสดงรายการ Booking อายุเกิน 90 วัน', 'booking_no, booking_number, customer_name, product_model, booking_date, booking_price', 'Use BOOKING_AGING_QUERY and SELECT the verified identifiers and dimensions; do not expose unnecessary PII'),
	('BOOKING_MODEL_RANKING', 'จัดอันดับรุ่นตาม Booking rows', 'product_model, booking_date, status', 'Apply the selected Booking scope, GROUP BY product_model, ORDER BY COUNT(*) DESC'),
	('BOOKING_BRANCH_RANKING', 'จัดอันดับสาขาตาม Booking rows', 'branch, branch_code, booking_date', 'Apply the selected Booking scope, GROUP BY branch, ORDER BY COUNT(*) DESC'),
	('BOOKING_CONVERSION_QUERY', 'คำนวณ Booking Conversion', 'status, booking_date', 'SELECT SUM(CASE WHEN status = ''Delivered'' THEN 1 ELSE 0 END) * 100.0 / NULLIF(COUNT(*), 0) FROM booking_transactions WHERE company_id = :company_id AND booking_date >= :start_date AND booking_date < :end_date'),
	('STOCK_CURRENT', 'นับ Stock ปัจจุบัน', 'stock_status, kmm_flag, company_id, physical identifiers', 'Apply current Free Stock and company ownership rules, deduplicate by stock_number/serial_number/engine_number/chassis_number, then COUNT(*)'),
	('STOCK_VALUE_CURRENT', 'รวมมูลค่า Stock ปัจจุบัน', 'stock_status, kmm_flag, msrp, physical identifiers', 'Apply STOCK_CURRENT scope and deduplication, then SUM(CAST(msrp AS REAL)) only for non-null MSRP'),
	('STOCK_AGING_QUERY', 'นับ Stock อายุเกิน 90 วัน', 'stock_age_days, stock_status, kmm_flag', 'Apply STOCK_CURRENT scope and WHERE stock_age_days > 90; GROUP BY product_model when a model breakdown is requested'),
	('STOCK_AGING_MODEL_RANKING', 'จัดอันดับรุ่นที่มี Stock อายุเกิน 90 วัน', 'product_model, stock_age_days, physical identifiers', 'Apply STOCK_AGING_QUERY, GROUP BY product_model, ORDER BY COUNT(*) DESC'),
	('STOCK_MODEL_RANKING', 'จัดอันดับรุ่นตาม Stock ค้าง', 'product_model, stock_age_days, physical identifiers', 'Apply STOCK_CURRENT scope, GROUP BY product_model, ORDER BY COUNT(*) DESC'),
	('STOCK_BRANCH_RANKING', 'จัดอันดับสาขาตาม Stock ค้าง', 'branch, stock_age_days, physical identifiers', 'Apply STOCK_CURRENT scope, GROUP BY branch, ORDER BY COUNT(*) DESC'),
	('STOCK_SLOW_MOVING_QUERY', 'นับ Stock อายุเกิน 180 วัน', 'stock_age_days, stock_status, kmm_flag', 'Apply STOCK_CURRENT scope and WHERE stock_age_days > 180'),
	('STOCK_SLOW_MOVING_MODEL_RANKING', 'จัดอันดับรุ่น Slow Moving', 'product_model, stock_age_days, physical identifiers', 'Apply STOCK_SLOW_MOVING_QUERY, GROUP BY product_model, ORDER BY COUNT(*) DESC'),
	('STOCK_MODEL_QUERY', 'ตอบ Stock ของรุ่นที่ระบุ', 'product_model, stock_status, physical identifiers', 'Apply STOCK_CURRENT scope and exact canonical model filter; return count and value with source scope');
--> statement-breakpoint

INSERT OR IGNORE INTO `kai_response_templates`
	(`intent`, `response_structure`)
VALUES
	('SALES_CURRENT', 'หัวข้อ; ช่วงข้อมูล; Sales Unit; Sales Value; แหล่งข้อมูล; หมายเหตุเมื่อข้อมูลไม่ครบ'),
	('SALES_MONTH_COMPARE', 'ช่วงปัจจุบัน; ช่วงเปรียบเทียบ; ค่าแต่ละช่วง; Difference; Growth %; แหล่งข้อมูล'),
	('SALES_YOY_COMPARE', 'เดือนและปีปัจจุบัน; เดือนและปีเปรียบเทียบ; ค่าแต่ละช่วง; Difference; Growth %; ขอบเขตข้อมูล'),
	('SALES_HISTORY_QUERY', 'ช่วงเดือน/ปีที่ผู้ใช้ระบุ; Sales Unit; Sales Value; GP เมื่อพร้อม; แหล่งข้อมูล'),
	('SALES_BRANCH_RANKING', 'ช่วงข้อมูล; อันดับสาขา; Sales Unit ต่อสาขา; ข้อจำกัดของข้อมูล'),
	('SALES_MODEL_RANKING', 'ช่วงข้อมูล; อันดับรุ่น; Sales Unit ต่อรุ่น; ข้อจำกัดของข้อมูล'),
	('SALES_ACHIEVEMENT_QUERY', 'Actual; Approved Target; Achievement %; Gap; สถานะความพร้อมของ Target'),
	('SALES_GP_QUERY', 'ช่วงข้อมูล; GP1; สถานะความครบถ้วนของ GP1; แหล่งข้อมูล'),
	('BOOKING_CURRENT', 'ช่วงข้อมูล; Booking rows; Booking Value เมื่อถาม; แหล่งข้อมูล; หมายเหตุ row-to-unit'),
	('BOOKING_MONTH_COMPARE', 'ช่วงปัจจุบัน; ช่วงก่อนหน้า; Booking แต่ละช่วง; Difference; Growth %'),
	('BOOKING_YOY_COMPARE', 'เดือนและปีทั้งสองช่วง; Booking แต่ละช่วง; Difference; Growth %'),
	('BOOKING_AGING_QUERY', 'Reference date; จำนวน Booking >90 วัน; Aging rule; แหล่งข้อมูล'),
	('BOOKING_AGING_LIST', 'Booking number; วันที่จอง; อายุวัน; รุ่น; สาขา; มูลค่าเมื่อมีสิทธิ์แสดง'),
	('BOOKING_CONVERSION_QUERY', 'ช่วงข้อมูล; Delivered rows; Booking rows; Conversion %; status rule'),
	('STOCK_CURRENT', 'Snapshot date; Current Stock Unit; current-stock rule; deduplication note; แหล่งข้อมูล'),
	('STOCK_VALUE_CURRENT', 'Snapshot date; Stock Unit; Stock Value; MSRP completeness; แหล่งข้อมูล'),
	('STOCK_AGING_QUERY', 'Snapshot/reference date; Stock >90 days; Aging rule; แหล่งข้อมูล'),
	('STOCK_AGING_MODEL_RANKING', 'Snapshot/reference date; รุ่น; Aging Stock Unit; อายุสูงสุด/ช่วงอายุเมื่อมีข้อมูล'),
	('STOCK_MODEL_RANKING', 'Snapshot date; อันดับรุ่น; Stock Unit; Stock Value เมื่อมีข้อมูล'),
	('STOCK_BRANCH_RANKING', 'Snapshot date; อันดับสาขา; Stock Unit; ข้อจำกัดของข้อมูล'),
	('STOCK_SLOW_MOVING_QUERY', 'Snapshot/reference date; Stock >180 days; Slow Moving rule; แหล่งข้อมูล'),
	('STOCK_SLOW_MOVING_MODEL_RANKING', 'Snapshot/reference date; รุ่น; Slow Moving Unit; แหล่งข้อมูล');
