-- Agriculture A14: factual Myanmar agriculture seed for Local Operations D1.
-- Only source-backed crop presence and historical/baseline calendar facts are
-- written here. No current stage, ownership, machine, customer, or opportunity
-- records are created.

INSERT OR IGNORE INTO `agri_sources` (`source_id`, `source_name`, `source_type`, `publisher`, `publication_date`, `source_geography`, `reference_uri`, `reliability_grade`, `notes`, `created_by`, `updated_by`) VALUES
  ('source-phase1a14-nattalin-rice', 'Nattalin 2025 rain-fed rice cultivation plan', 'RESEARCH_BASELINE', 'Myanmar Digital News / Department of Agriculture', '2025-06-09', 'TOWNSHIP', 'https://mdn.gov.mm/en/nattalin-township-plans-cultivate-more-110000-acres-rain-fed-rice', 'V1', 'Evidence: 2025 rain-fed rice cultivation plan, approximately 110,262 acres. Planting-plan evidence only; no current crop stage or harvest date inferred. Verification: V1_RESEARCH_BASELINE.', 'local-agriculture-phase1a14', 'local-agriculture-phase1a14'),
  ('source-phase1a14-nattalin-groundnut', 'Nattalin winter 2024/25 groundnut cultivation', 'RESEARCH_BASELINE', 'Myanmar Digital News / Township Department of Agriculture', '2025-01-11', 'TOWNSHIP', 'https://www.mdn.gov.mm/en/nattalin-township-completes-cultivation-7532-acres-oilseed-crops', 'V1', 'Evidence: winter 2024/25 cultivation of approximately 2,730 acres of groundnut. Presence evidence only; no current crop stage inferred. Verification: V1_RESEARCH_BASELINE.', 'local-agriculture-phase1a14', 'local-agriculture-phase1a14'),
  ('source-phase1a14-nattalin-sesame', 'Nattalin winter 2024/25 sesame cultivation', 'RESEARCH_BASELINE', 'Myanmar Digital News / Township Department of Agriculture', '2025-01-11', 'TOWNSHIP', 'https://www.mdn.gov.mm/en/nattalin-township-completes-cultivation-7532-acres-oilseed-crops', 'V1', 'Evidence: winter 2024/25 cultivation of approximately 1,988 acres of sesame. Presence evidence only; no current crop stage inferred. Verification: V1_RESEARCH_BASELINE.', 'local-agriculture-phase1a14', 'local-agriculture-phase1a14'),
  ('source-phase1a14-mudon-rice', 'Mudon 2024/25 monsoon rice harvest', 'RESEARCH_BASELINE', 'Myanmar Digital News / Township Agriculture Department', '2024-12-26', 'TOWNSHIP', 'https://mdn.gov.mm/en/over-75000-acres-monsoon-paddy-reaped-mudon-township', 'V1', 'Evidence: more than 75,000 acres of monsoon rice reaped in Mudon; harvest began in the first week of November 2024 and was complete by December 2024 for the 2024/25 season. Historical calendar only; not a current stage. Verification: V1_RESEARCH_BASELINE.', 'local-agriculture-phase1a14', 'local-agriculture-phase1a14'),
  ('source-phase1a14-mudon-rubber', 'Mudon rubber research and processing activity', 'RESEARCH_BASELINE', 'Myanmar Digital News / Department of Agriculture', '2026-07-01', 'TOWNSHIP', 'https://www.mdn.gov.mm/en/agri-dept-seeks-sell-over-220-tonnes-rubber', 'V1', 'Evidence: Perennial Crops Research and Technology Development Farm activity in Mudon and supporting Mon rubber context. No township acreage asserted; no current crop stage inferred. Verification: V1_RESEARCH_BASELINE.', 'local-agriculture-phase1a14', 'local-agriculture-phase1a14'),
  ('source-phase1a14-kyaikmaraw-rubber', 'Kyaikmaraw local rubber sheet processing', 'RESEARCH_BASELINE', 'Myanmar Digital News', '2024-02-29', 'TOWNSHIP', 'https://www.mdn.gov.mm/en/kyaikmaraw-rubber-sheets-meet-export-standards-china-malaysia', 'V1', 'Evidence: local refined rubber sheet production and local raw-material trade in Kyaikmaraw. Presence confirmed; no cultivated acreage or current crop stage inferred. Verification: V1_RESEARCH_BASELINE.', 'local-agriculture-phase1a14', 'local-agriculture-phase1a14'),
  ('source-phase1a14-thanbyuzayat-rubber', 'Thanbyuzayat rubber group processing activity', 'RESEARCH_BASELINE', 'Myanmar Digital News', '2026-07-10', 'TOWNSHIP', 'https://mdn.gov.mm/en/upgrading-myanmar-rubber-through-group-processing-factories', 'V1', 'Evidence: group processing factory activity in Thanbyuzayat. Local industry evidence supports PROBABLE presence only; no cultivated acreage or current crop stage inferred. Verification: V1_RESEARCH_BASELINE.', 'local-agriculture-phase1a14', 'local-agriculture-phase1a14'),
  ('source-phase1a14-mawlamyine-rubber', 'Mawlamyine rubber institutional and regional context', 'RESEARCH_BASELINE', 'Myanmar Digital News / Department of Agriculture', '2026-07-01', 'REGIONAL', 'https://www.mdn.gov.mm/en/agri-dept-seeks-sell-over-220-tonnes-rubber', 'V1', 'Evidence: Perennial Crops Research and Technology Development Department activity in Mawlamyine and regional rubber production context. PROBABLE only; no township acreage or current crop stage inferred. Verification: V1_RESEARCH_BASELINE.', 'local-agriculture-phase1a14', 'local-agriculture-phase1a14'),
  ('source-phase1a14-fao-rice-national', 'FAO GIEWS Myanmar rice baseline', 'AUTHORITATIVE_BASELINE', 'FAO GIEWS', '2026-02-20', 'NATIONAL_REGIONAL', 'https://www.fao.org/giews/countrybrief/country.jsp?code=MM', 'V4', 'Evidence: main paddy is approximately 80% of annual output; monsoon season is roughly June–October; the 2025/26 main harvest finalized in December 2025; secondary paddy was in vegetative to early reproductive stages around February 2026. National/regional baseline only; must not change a township current stage.', 'local-agriculture-phase1a14', 'local-agriculture-phase1a14'),
  ('source-phase1a14-rubber-national-regional', 'Myanmar and southern-region rubber baseline', 'RESEARCH_BASELINE', 'Myanmar Digital News / Myanmar Rubber Planters and Producers Association', '2026-05-04', 'NATIONAL_REGIONAL', 'https://www.mdn.gov.mm/en/myanmar-exports-about-300000-tonnes-rubber-2025-2026-fy-earning-over-us400-million', 'V1', 'Evidence: Myanmar has approximately 1.64 million acres of rubber plantations, about 850,000 acres under tapping/extraction, Mon State is the leading producing area, and Kayin is a major producing area. General peak production/tapping is October–January; persistent rain can interrupt production. National acreage only; do not copy acreage to townships. Regional baseline only; current township stage remains UNKNOWN.', 'local-agriculture-phase1a14', 'local-agriculture-phase1a14');
--> statement-breakpoint
INSERT OR IGNORE INTO `agri_seasons` (`season_id`, `season_code`, `season_name`, `country_code`, `notes`, `created_by`, `updated_by`) VALUES
  ('season-main-monsoon', 'MAIN_MONSOON', 'Main monsoon', 'MM', 'Season label used by the Phase 1A.14 historical Mudon rice calendar. Source: source-phase1a14-fao-rice-national.', 'local-agriculture-phase1a14', 'local-agriculture-phase1a14');
--> statement-breakpoint
UPDATE `agri_crop_locations`
SET `presence_status` = 'CONFIRMED_PRESENT', `importance_level` = 'MAJOR', `evidence_geography` = 'TOWNSHIP', `evidence_year` = 2025, `source_id` = 'source-phase1a14-nattalin-rice', `confidence_grade` = 'V1', `cultivated_area` = '110262', `cultivated_area_unit` = 'acres', `cultivated_area_year` = 2025, `local_verified` = 0, `verified_by` = NULL, `verified_at` = NULL, `notes` = '2025 rain-fed rice cultivation plan, approximately 110,262 acres. Current stage and harvest remain UNKNOWN.'
WHERE `location_id` = 'MM-BGO-NATTALIN' AND `crop_id` = 'crop-rice' AND `presence_status` = 'UNKNOWN';
--> statement-breakpoint
UPDATE `agri_crop_locations`
SET `presence_status` = 'CONFIRMED_PRESENT', `importance_level` = 'UNKNOWN', `evidence_geography` = 'TOWNSHIP', `evidence_year` = 2024, `source_id` = 'source-phase1a14-nattalin-groundnut', `confidence_grade` = 'V1', `cultivated_area` = '2730', `cultivated_area_unit` = 'acres', `cultivated_area_year` = 2024, `local_verified` = 0, `verified_by` = NULL, `verified_at` = NULL, `notes` = 'Winter 2024/25 cultivation approximately 2,730 acres. Current stage remains UNKNOWN.'
WHERE `location_id` = 'MM-BGO-NATTALIN' AND `crop_id` = 'crop-groundnut' AND `presence_status` = 'UNKNOWN';
--> statement-breakpoint
UPDATE `agri_crop_locations`
SET `presence_status` = 'CONFIRMED_PRESENT', `importance_level` = 'UNKNOWN', `evidence_geography` = 'TOWNSHIP', `evidence_year` = 2024, `source_id` = 'source-phase1a14-nattalin-sesame', `confidence_grade` = 'V1', `cultivated_area` = '1988', `cultivated_area_unit` = 'acres', `cultivated_area_year` = 2024, `local_verified` = 0, `verified_by` = NULL, `verified_at` = NULL, `notes` = 'Winter 2024/25 cultivation approximately 1,988 acres. Current stage remains UNKNOWN.'
WHERE `location_id` = 'MM-BGO-NATTALIN' AND `crop_id` = 'crop-sesame' AND `presence_status` = 'UNKNOWN';
--> statement-breakpoint
UPDATE `agri_crop_locations`
SET `presence_status` = 'CONFIRMED_PRESENT', `importance_level` = 'MAJOR', `evidence_geography` = 'TOWNSHIP', `evidence_year` = 2024, `source_id` = 'source-phase1a14-mudon-rice', `confidence_grade` = 'V1', `cultivated_area` = '>75000', `cultivated_area_unit` = 'acres', `cultivated_area_year` = 2024, `local_verified` = 0, `verified_by` = NULL, `verified_at` = NULL, `notes` = '2024/25 monsoon rice: more than 75,000 acres reaped; harvest began in early November and completed in December. Historical calendar only; current stage remains UNKNOWN.'
WHERE `location_id` = 'MM-MON-MUDON' AND `crop_id` = 'crop-rice' AND `presence_status` = 'UNKNOWN';
--> statement-breakpoint
UPDATE `agri_crop_locations`
SET `presence_status` = 'CONFIRMED_PRESENT', `importance_level` = 'UNKNOWN', `evidence_geography` = 'TOWNSHIP', `evidence_year` = NULL, `source_id` = 'source-phase1a14-mudon-rubber', `confidence_grade` = 'V1', `cultivated_area` = NULL, `cultivated_area_unit` = NULL, `cultivated_area_year` = NULL, `local_verified` = 0, `verified_by` = NULL, `verified_at` = NULL, `notes` = 'Rubber research and processing activity supports presence. No township acreage or current stage inferred.'
WHERE `location_id` = 'MM-MON-MUDON' AND `crop_id` = 'crop-rubber' AND `presence_status` = 'UNKNOWN';
--> statement-breakpoint
UPDATE `agri_crop_locations`
SET `presence_status` = 'CONFIRMED_PRESENT', `importance_level` = 'UNKNOWN', `evidence_geography` = 'TOWNSHIP', `evidence_year` = 2024, `source_id` = 'source-phase1a14-kyaikmaraw-rubber', `confidence_grade` = 'V1', `cultivated_area` = NULL, `cultivated_area_unit` = NULL, `cultivated_area_year` = NULL, `local_verified` = 0, `verified_by` = NULL, `verified_at` = NULL, `notes` = 'Local rubber sheet and raw-material processing activity supports presence. No cultivated acreage or current stage inferred.'
WHERE `location_id` = 'MM-MON-KYAIKMARAW' AND `crop_id` = 'crop-rubber' AND `presence_status` = 'UNKNOWN';
--> statement-breakpoint
UPDATE `agri_crop_locations`
SET `presence_status` = 'PROBABLE', `importance_level` = 'UNKNOWN', `evidence_geography` = 'TOWNSHIP', `evidence_year` = NULL, `source_id` = 'source-phase1a14-thanbyuzayat-rubber', `confidence_grade` = 'V1', `cultivated_area` = NULL, `cultivated_area_unit` = NULL, `cultivated_area_year` = NULL, `local_verified` = 0, `verified_by` = NULL, `verified_at` = NULL, `notes` = 'Current group-processing activity supports PROBABLE rubber presence. No cultivated acreage or current stage inferred.'
WHERE `location_id` = 'MM-MON-THANBYUZAYAT' AND `crop_id` = 'crop-rubber' AND `presence_status` = 'UNKNOWN';
--> statement-breakpoint
UPDATE `agri_crop_locations`
SET `presence_status` = 'PROBABLE', `importance_level` = 'UNKNOWN', `evidence_geography` = 'REGIONAL', `evidence_year` = NULL, `source_id` = 'source-phase1a14-mawlamyine-rubber', `confidence_grade` = 'V1', `cultivated_area` = NULL, `cultivated_area_unit` = NULL, `cultivated_area_year` = NULL, `local_verified` = 0, `verified_by` = NULL, `verified_at` = NULL, `notes` = 'Institutional and regional rubber context supports PROBABLE presence only. No township acreage or current stage inferred.'
WHERE `location_id` = 'MM-MON-MAWLAMYINE' AND `crop_id` = 'crop-rubber' AND `presence_status` = 'UNKNOWN';
--> statement-breakpoint
INSERT OR IGNORE INTO `agri_crop_calendars` (`calendar_record_id`, `location_id`, `crop_id`, `season_id`, `crop_year`, `stage_code`, `baseline_start_date`, `baseline_end_date`, `source_geography`, `source_id`, `source_publication_date`, `verification_level`, `confidence_score`, `inherited_from_location_id`, `weather_adjusted`, `calendar_shift_status`, `calendar_shift_days`, `local_verified`, `verified_by`, `verified_at`, `created_by`, `updated_by`) VALUES
  ('calendar-phase1a14-nattalin-rice-2025-sowing', 'MM-BGO-NATTALIN', 'crop-rice', NULL, 2025, 'SOWING', '2025-06', NULL, 'TOWNSHIP', 'source-phase1a14-nattalin-rice', '2025-06-09', 'V1', 25, NULL, 0, 'UNKNOWN', NULL, 0, NULL, NULL, 'local-agriculture-phase1a14', 'local-agriculture-phase1a14'),
  ('calendar-phase1a14-mudon-rice-2024-25-harvest', 'MM-MON-MUDON', 'crop-rice', 'season-main-monsoon', 2024, 'HARVEST', '2024-11', '2024-12', 'TOWNSHIP', 'source-phase1a14-mudon-rice', '2024-12-26', 'V1', 25, NULL, 0, 'UNKNOWN', NULL, 0, NULL, NULL, 'local-agriculture-phase1a14', 'local-agriculture-phase1a14');
--> statement-breakpoint
-- No agri_calendar_estimates, agri_field_verifications, agri_service_providers,
-- agri_crop_weather_state, or agri_opportunities are seeded in Phase 1A.14.
