ALTER TABLE `booking_transactions` ADD `booking_year` integer;--> statement-breakpoint
ALTER TABLE `booking_transactions` ADD `booking_month` integer;--> statement-breakpoint
ALTER TABLE `booking_transactions` ADD `branch_code` text;--> statement-breakpoint
ALTER TABLE `booking_transactions` ADD `branch_name` text;--> statement-breakpoint
ALTER TABLE `booking_transactions` ADD `salesperson_code` text;--> statement-breakpoint
ALTER TABLE `booking_transactions` ADD `salesperson_name` text;--> statement-breakpoint
ALTER TABLE `booking_transactions` ADD `product_type` text;--> statement-breakpoint
ALTER TABLE `booking_transactions` ADD `product_model` text;--> statement-breakpoint
ALTER TABLE `booking_transactions` ADD `customer_name` text;--> statement-breakpoint
ALTER TABLE `booking_transactions` ADD `booking_price` text;--> statement-breakpoint
ALTER TABLE `booking_transactions` ADD `deposit_amount` text;--> statement-breakpoint
ALTER TABLE `booking_transactions` ADD `booking_status` text;--> statement-breakpoint
ALTER TABLE `booking_transactions` ADD `purchase_status` text;--> statement-breakpoint
ALTER TABLE `stock_transactions` ADD `stock_date` text;--> statement-breakpoint
ALTER TABLE `stock_transactions` ADD `branch_code` text;--> statement-breakpoint
ALTER TABLE `stock_transactions` ADD `branch_name` text;--> statement-breakpoint
ALTER TABLE `stock_transactions` ADD `product_type` text;--> statement-breakpoint
ALTER TABLE `stock_transactions` ADD `product_group` text;--> statement-breakpoint
ALTER TABLE `stock_transactions` ADD `product_model` text;--> statement-breakpoint
ALTER TABLE `stock_transactions` ADD `kmm_flag` integer;--> statement-breakpoint
ALTER TABLE `stock_transactions` ADD `msrp` text;--> statement-breakpoint
ALTER TABLE `stock_transactions` ADD `stock_status` text;--> statement-breakpoint
ALTER TABLE `stock_transactions` ADD `stock_number` text;--> statement-breakpoint
ALTER TABLE `stock_transactions` ADD `serial_number` text;--> statement-breakpoint
ALTER TABLE `stock_transactions` ADD `engine_number` text;--> statement-breakpoint
ALTER TABLE `stock_transactions` ADD `chassis_number` text;--> statement-breakpoint
ALTER TABLE `stock_transactions` ADD `stock_age_days` integer;--> statement-breakpoint
ALTER TABLE `stock_transactions` ADD `snapshot_date` text;