import { sql } from "drizzle-orm";
import {
  index,
  integer,
  real,
  sqliteTable,
  text,
  uniqueIndex,
} from "drizzle-orm/sqlite-core";

const timestamps = {
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  createdBy: text("created_by").notNull(),
  updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  updatedBy: text("updated_by").notNull(),
};

export const companies = sqliteTable(
  "companies",
  {
    id: text("id").primaryKey(),
    tenantId: text("tenant_id").notNull(),
    companyId: text("company_id").notNull(),
    companyName: text("company_name").notNull(),
    companyCode: text("company_code").notNull().unique(),
    legalName: text("legal_name").notNull().default(""),
    logoUrl: text("logo_url").notNull().default(""),
    taxId: text("tax_id").notNull().default(""),
    registrationNumber: text("registration_number").notNull().default(""),
    businessType: text("business_type").notNull().default(""),
    industry: text("industry").notNull().default(""),
    establishedYear: integer("established_year"),
    website: text("website").notNull().default(""),
    email: text("email").notNull().default(""),
    phone: text("phone").notNull().default(""),
    address: text("address").notNull().default(""),
    description: text("description").notNull().default(""),
    status: text("status").notNull().default("active"),
    publishedAt: text("published_at"),
    ...timestamps,
  },
  (table) => [
    uniqueIndex("companies_company_id_unique").on(table.companyId),
  ],
);

export const companyUsers = sqliteTable(
  "company_users",
  {
    id: text("id").primaryKey(),
    tenantId: text("tenant_id").notNull(),
    companyId: text("company_id").notNull(),
    userId: text("user_id").notNull(),
    email: text("email").notNull().default(""),
    role: text("role").notNull().default("viewer"),
    status: text("status").notNull().default("active"),
    ...timestamps,
  },
  (table) => [
    uniqueIndex("company_users_company_user_unique").on(
      table.companyId,
      table.userId,
    ),
  ],
);

export const branches = sqliteTable(
  "branches",
  {
    id: text("id").primaryKey(),
    tenantId: text("tenant_id").notNull(),
    companyId: text("company_id").notNull(),
    branchName: text("branch_name").notNull(),
    branchCode: text("branch_code").notNull(),
    region: text("region").notNull().default(""),
    township: text("township").notNull().default(""),
    address: text("address").notNull().default(""),
    manager: text("manager").notNull().default(""),
    phone: text("phone").notNull().default(""),
    email: text("email").notNull().default(""),
    latitude: text("latitude").notNull().default(""),
    longitude: text("longitude").notNull().default(""),
    timeZone: text("time_zone").notNull().default("Asia/Yangon"),
    users: integer("users").notNull().default(0),
    hasTransactions: integer("has_transactions", { mode: "boolean" })
      .notNull()
      .default(false),
    status: text("status").notNull().default("active"),
    ...timestamps,
  },
  (table) => [
    uniqueIndex("branches_company_code_unique").on(
      table.companyId,
      table.branchCode,
    ),
  ],
);

export const departments = sqliteTable(
  "departments",
  {
    id: text("id").primaryKey(),
    tenantId: text("tenant_id").notNull(),
    companyId: text("company_id").notNull(),
    departmentName: text("department_name").notNull(),
    departmentCode: text("department_code").notNull(),
    branchId: text("branch_id").notNull().default(""),
    head: text("head").notNull().default(""),
    users: integer("users").notNull().default(0),
    status: text("status").notNull().default("active"),
    ...timestamps,
  },
  (table) => [
    uniqueIndex("departments_company_code_unique").on(
      table.companyId,
      table.departmentCode,
    ),
  ],
);

export const fiscalYears = sqliteTable("fiscal_years", {
  id: text("id").primaryKey(),
  tenantId: text("tenant_id").notNull(),
  companyId: text("company_id").notNull(),
  fiscalYearName: text("fiscal_year_name").notNull(),
  startMonth: integer("start_month").notNull(),
  startDay: integer("start_day").notNull(),
  endMonth: integer("end_month").notNull(),
  endDay: integer("end_day").notNull(),
  currentFiscalYear: integer("current_fiscal_year", { mode: "boolean" })
    .notNull()
    .default(true),
  status: text("status").notNull().default("active"),
  ...timestamps,
});

export const companyCurrencies = sqliteTable("company_currencies", {
  id: text("id").primaryKey(),
  tenantId: text("tenant_id").notNull(),
  companyId: text("company_id").notNull(),
  primaryCurrency: text("primary_currency").notNull().default("MMK"),
  displayCurrency: text("display_currency").notNull().default("MMK"),
  currencySymbol: text("currency_symbol").notNull().default("K"),
  decimalPlaces: integer("decimal_places").notNull().default(0),
  numberFormat: text("number_format").notNull().default("1,234.56"),
  negativeNumberFormat: text("negative_number_format")
    .notNull()
    .default("-1,234.56"),
  exchangeRateSource: text("exchange_rate_source")
    .notNull()
    .default("manual"),
  manualExchangeRate: text("manual_exchange_rate").notNull().default("1"),
  lastRateUpdate: text("last_rate_update"),
  status: text("status").notNull().default("active"),
  ...timestamps,
});

export const companyLocalizations = sqliteTable("company_localizations", {
  id: text("id").primaryKey(),
  tenantId: text("tenant_id").notNull(),
  companyId: text("company_id").notNull(),
  defaultLanguage: text("default_language").notNull().default("en"),
  fallbackLanguage: text("fallback_language").notNull().default("th"),
  defaultTimeZone: text("default_time_zone")
    .notNull()
    .default("Asia/Yangon"),
  dateFormat: text("date_format").notNull().default("DD/MM/YYYY"),
  timeFormat: text("time_format").notNull().default("24-hour"),
  firstDayOfWeek: text("first_day_of_week").notNull().default("Monday"),
  status: text("status").notNull().default("active"),
  ...timestamps,
});

export const workingCalendars = sqliteTable("working_calendars", {
  id: text("id").primaryKey(),
  tenantId: text("tenant_id").notNull(),
  companyId: text("company_id").notNull(),
  workingDays: text("working_days").notNull().default("[]"),
  weekendDays: text("weekend_days").notNull().default("[]"),
  workingStartTime: text("working_start_time").notNull().default("08:00"),
  workingEndTime: text("working_end_time").notNull().default("17:00"),
  status: text("status").notNull().default("active"),
  ...timestamps,
});

export const holidays = sqliteTable("holidays", {
  id: text("id").primaryKey(),
  tenantId: text("tenant_id").notNull(),
  companyId: text("company_id").notNull(),
  branchId: text("branch_id").notNull().default(""),
  holidayName: text("holiday_name").notNull(),
  holidayDate: text("holiday_date").notNull(),
  repeatAnnually: integer("repeat_annually", { mode: "boolean" })
    .notNull()
    .default(false),
  holidayType: text("holiday_type").notNull().default("company"),
  status: text("status").notNull().default("active"),
  ...timestamps,
});

export const companySettingDrafts = sqliteTable("company_setting_drafts", {
  id: text("id").primaryKey(),
  tenantId: text("tenant_id").notNull(),
  companyId: text("company_id").notNull().unique(),
  payload: text("payload").notNull(),
  revision: integer("revision").notNull().default(1),
  status: text("status").notNull().default("draft"),
  ...timestamps,
});

export const auditLogs = sqliteTable("audit_logs", {
  id: text("id").primaryKey(),
  tenantId: text("tenant_id").notNull(),
  companyId: text("company_id").notNull(),
  userId: text("user_id").notNull(),
  action: text("action").notNull(),
  entity: text("entity").notNull(),
  entityId: text("entity_id").notNull(),
  oldValue: text("old_value"),
  newValue: text("new_value"),
  ipAddress: text("ip_address"),
  device: text("device"),
  status: text("status").notNull().default("recorded"),
  ...timestamps,
});

export const salesTransactions = sqliteTable(
  "sales_transactions",
  {
    id: text("id").primaryKey(),
    tenantId: text("tenant_id").notNull(),
    companyId: text("company_id").notNull(),
    importId: text("import_id").notNull(),
    importYear: integer("import_year").notNull(),
    importMonth: integer("import_month").notNull(),
    saleDate: text("sale_date").notNull(),
    invoiceNo: text("invoice_no").notNull(),
    branch: text("branch").notNull(),
    modelCode: text("model_code").notNull(),
    employeeCode: text("employee_code").notNull().default(""),
    quantity: integer("quantity").notNull(),
    saleAmount: text("sale_amount").notNull(),
    productType: text("product_type"),
    model: text("model"),
    finalReceived: text("final_received"),
    netReceived: text("net_received"),
    gp1: text("gp1"),
    expense: text("expense"),
    // Imported CPI column "Total". Nullable so historic Sales imports remain
    // valid until Commission is present in an approved source workbook.
    commission: text("commission"),
    salespersonCode: text("salesperson_code"),
    salespersonName: text("salesperson_name"),
    createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
    createdBy: text("created_by").notNull(),
  },
  (table) => [
    index("sales_scope_invoice_idx").on(
      table.companyId,
      table.importYear,
      table.importMonth,
      table.invoiceNo,
    ),
  ],
);

export const salespersonIdentityAliases = sqliteTable(
  "salesperson_identity_aliases",
  {
    id: text("id").primaryKey(),
    tenantId: text("tenant_id").notNull(),
    companyId: text("company_id").notNull(),
    sourceSalespersonCode: text("source_salesperson_code"),
    sourceEmployeeCode: text("source_employee_code"),
    sourceSalespersonName: text("source_salesperson_name").notNull(),
    sourceBranch: text("source_branch").notNull(),
    canonicalEmployeeCode: text("canonical_employee_code").notNull(),
    canonicalSalespersonCode: text("canonical_salesperson_code").notNull(),
    evidence: text("evidence").notNull(),
    createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
    createdBy: text("created_by").notNull(),
  },
  (table) => [
    index("salesperson_identity_alias_company_scope_idx").on(table.companyId, table.sourceBranch, table.sourceSalespersonName),
  ],
);

export const dataImportHistory = sqliteTable("data_" + "import_" + "history", {
  id: text("id").primaryKey(),
  tenantId: text("tenant_id").notNull(),
  companyId: text("company_id").notNull(),
  module: text("module").notNull(),
  importYear: integer("import_year").notNull(),
  importMonth: integer("import_month").notNull(),
  filename: text("filename").notNull(),
  status: text("status").notNull(),
  totalRows: integer("total_rows").notNull().default(0),
  validRows: integer("valid_rows").notNull().default(0),
  warningRows: integer("warning_rows").notNull().default(0),
  errorRows: integer("error_rows").notNull().default(0),
  durationMs: integer("duration_ms").notNull().default(0),
  errorReport: text("error_report"),
  importedBy: text("imported_by").notNull(),
  importedAt: text("imported_at").notNull().default(sql`CURRENT_TIMESTAMP`),
});

export const dataColumnMappings = sqliteTable(
  "data_column_mappings",
  {
    id: text("id").primaryKey(),
    tenantId: text("tenant_id").notNull(),
    companyId: text("company_id").notNull(),
    module: text("module").notNull(),
    mapping: text("mapping").notNull(),
    updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`),
    updatedBy: text("updated_by").notNull(),
  },
  (table) => [
    uniqueIndex("data_column_mappings_scope_unique").on(
      table.companyId,
      table.module,
    ),
  ],
);

export const salespersonMaster = sqliteTable(
  "salesperson_master",
  {
    id: text("id").primaryKey(),
    tenantId: text("tenant_id").notNull(),
    companyId: text("company_id").notNull(),
    employeeCode: text("employee_code").notNull(),
    salespersonCode: text("salesperson_code").notNull(),
    salespersonName: text("salesperson_name").notNull(),
    status: text("status").notNull().default("active"),
    createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
    createdBy: text("created_by").notNull(),
    updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`),
    updatedBy: text("updated_by").notNull(),
  },
  (table) => [
    uniqueIndex("salesperson_master_employee_unique").on(table.companyId, table.employeeCode),
    uniqueIndex("salesperson_master_code_unique").on(table.companyId, table.salespersonCode),
  ],
);

/**
 * Approved, versioned business targets. Empty dimension keys represent an
 * explicit company-wide scope so SQLite can enforce one record per exact
 * target scope and source version without NULL-unique ambiguity.
 */
export const businessTargets = sqliteTable(
  "business_targets",
  {
    id: text("id").primaryKey(),
    tenantId: text("tenant_id").notNull(),
    companyId: text("company_id").notNull(),
    targetYear: integer("target_year").notNull(),
    targetMonth: integer("target_month").notNull(),
    metric: text("metric").notNull(),
    targetValue: text("target_value").notNull(),
    productGroup: text("product_group").notNull().default(""),
    branchId: text("branch_id").notNull().default(""),
    salespersonId: text("salesperson_id").notNull().default(""),
    source: text("source").notNull(),
    sourceVersion: text("source_version").notNull(),
    approvalStatus: text("approval_status").notNull().default("approved"),
    effectiveFrom: text("effective_from").notNull(),
    createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
    createdBy: text("created_by").notNull(),
    updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`),
    updatedBy: text("updated_by").notNull(),
  },
  (table) => [
    uniqueIndex("business_targets_exact_version_unique").on(
      table.companyId,
      table.targetYear,
      table.targetMonth,
      table.metric,
      table.productGroup,
      table.branchId,
      table.salespersonId,
      table.sourceVersion,
    ),
    index("business_targets_runtime_lookup_idx").on(
      table.companyId,
      table.targetYear,
      table.targetMonth,
      table.metric,
      table.productGroup,
      table.branchId,
      table.salespersonId,
      table.approvalStatus,
      table.effectiveFrom,
    ),
  ],
);

export const bookingTransactions = sqliteTable("booking_transactions", {
  id: text("id").primaryKey(),
  tenantId: text("tenant_id").notNull(),
  companyId: text("company_id").notNull(),
  importId: text("import_id").notNull(),
  importYear: integer("import_year").notNull(),
  importMonth: integer("import_month").notNull(),
  businessWeek: integer("business_week"),
  bookingDate: text("booking_date").notNull(),
  bookingNo: text("booking_no").notNull(),
  bookingNumber: text("booking_number"),
  branch: text("branch").notNull(),
  customer: text("customer").notNull(),
  product: text("product").notNull(),
  status: text("status").notNull(),
  bookingYear: integer("booking_year"),
  bookingMonth: integer("booking_month"),
  branchCode: text("branch_code"),
  branchName: text("branch_name"),
  salespersonCode: text("salesperson_code"),
  salespersonName: text("salesperson_name"),
  productType: text("product_type"),
  productModel: text("product_model"),
  customerName: text("customer_name"),
  bookingPrice: text("booking_price"),
  depositAmount: text("deposit_amount"),
  bookingStatus: text("booking_status"),
  purchaseStatus: text("purchase_status"),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  createdBy: text("created_by").notNull(),
});

export const stockTransactions = sqliteTable("stock_transactions", {
  id: text("id").primaryKey(),
  tenantId: text("tenant_id").notNull(),
  companyId: text("company_id").notNull(),
  importId: text("import_id").notNull(),
  importYear: integer("import_year").notNull(),
  importMonth: integer("import_month").notNull(),
  businessWeek: integer("business_week"),
  asOfDate: text("as_of_date").notNull(),
  branch: text("branch").notNull(),
  product: text("product").notNull(),
  quantity: integer("quantity").notNull(),
  stockDate: text("stock_date"),
  branchCode: text("branch_code"),
  branchName: text("branch_name"),
  productType: text("product_type"),
  productGroup: text("product_group"),
  productModel: text("product_model"),
  kmmFlag: integer("kmm_flag"),
  msrp: text("msrp"),
  stockStatus: text("stock_status"),
  stockNumber: text("stock_number"),
  serialNumber: text("serial_number"),
  engineNumber: text("engine_number"),
  chassisNumber: text("chassis_number"),
  stockAgeDays: integer("stock_age_days"),
  snapshotDate: text("snapshot_date"),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  createdBy: text("created_by").notNull(),
});

export const dailyManagementInputs = sqliteTable(
  "daily_management_inputs",
  {
    id: text("id").primaryKey(),
    tenantId: text("tenant_id").notNull(),
    companyId: text("company_id").notNull(),
    reportDate: text("report_date").notNull(),
    branch: text("branch").notNull(),
    draftPayload: text("draft_payload").notNull(),
    publishedPayload: text("published_payload"),
    revision: integer("revision").notNull().default(1),
    savedAt: text("saved_at").notNull(),
    publishedAt: text("published_at"),
    createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
    createdBy: text("created_by").notNull(),
    updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`),
    updatedBy: text("updated_by").notNull(),
  },
  (table) => [
    uniqueIndex("daily_management_inputs_scope_unique").on(
      table.companyId,
      table.reportDate,
      table.branch,
    ),
    index("daily_management_inputs_latest_idx").on(
      table.companyId,
      table.updatedAt,
    ),
  ],
);

/**
 * Agriculture master and operational tables live in Operations D1. Master
 * records are global; company-scoped records carry company_id and are always
 * queried after company authorization.
 */
export const agriCrops = sqliteTable(
  "agri_crops",
  {
    cropId: text("crop_id").primaryKey(),
    cropCode: text("crop_code").notNull().unique(),
    cropName: text("crop_name").notNull(),
    cropCycleType: text("crop_cycle_type").notNull(),
    alternateNames: text("alternate_names").notNull().default("[]"),
    isActive: integer("is_active", { mode: "boolean" }).notNull().default(true),
    createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
    createdBy: text("created_by").notNull(),
    updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`),
    updatedBy: text("updated_by").notNull(),
  },
  (table) => [index("agri_crops_active_idx").on(table.isActive, table.cropCode)],
);

export const agriCropStages = sqliteTable(
  "agri_crop_stages",
  {
    stageId: text("stage_id").primaryKey(),
    cropId: text("crop_id").notNull(),
    stageCode: text("stage_code").notNull(),
    stageName: text("stage_name").notNull(),
    displayOrder: integer("display_order").notNull(),
    isActive: integer("is_active", { mode: "boolean" }).notNull().default(true),
    createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
    createdBy: text("created_by").notNull(),
    updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`),
    updatedBy: text("updated_by").notNull(),
  },
  (table) => [
    uniqueIndex("agri_crop_stages_crop_code_unique").on(table.cropId, table.stageCode),
    index("agri_crop_stages_crop_order_idx").on(table.cropId, table.displayOrder),
  ],
);

export const agriSeasons = sqliteTable(
  "agri_seasons",
  {
    seasonId: text("season_id").primaryKey(),
    seasonCode: text("season_code").notNull().unique(),
    seasonName: text("season_name").notNull(),
    countryCode: text("country_code"),
    notes: text("notes"),
    isActive: integer("is_active", { mode: "boolean" }).notNull().default(true),
    createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
    createdBy: text("created_by").notNull(),
    updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`),
    updatedBy: text("updated_by").notNull(),
  },
  (table) => [index("agri_seasons_active_idx").on(table.isActive, table.seasonCode)],
);

export const agriLocations = sqliteTable(
  "agri_locations",
  {
    locationId: text("location_id").primaryKey(),
    countryCode: text("country_code").notNull(),
    stateRegionCode: text("state_region_code"),
    stateRegionName: text("state_region_name"),
    districtCode: text("district_code"),
    districtName: text("district_name"),
    townshipCode: text("township_code"),
    townshipName: text("township_name"),
    canonicalName: text("canonical_name").notNull(),
    alternateNames: text("alternate_names").notNull().default("[]"),
    myanmarName: text("myanmar_name"),
    latitude: text("latitude"),
    longitude: text("longitude"),
    adminVersion: text("admin_version").notNull(),
    source: text("source").notNull(),
    sourceDate: text("source_date"),
    geographyLevel: text("geography_level").notNull().default("TOWNSHIP"),
    kmmBranchCode: text("kmm_branch_code"),
    salesTerritoryId: text("sales_territory_id"),
    isActive: integer("is_active", { mode: "boolean" }).notNull().default(true),
    validFrom: text("valid_from"),
    validTo: text("valid_to"),
    createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
    createdBy: text("created_by").notNull(),
    updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`),
    updatedBy: text("updated_by").notNull(),
  },
  (table) => [
    uniqueIndex("agri_locations_country_canonical_unique").on(table.countryCode, table.canonicalName),
    index("agri_locations_township_lookup_idx").on(table.countryCode, table.stateRegionCode, table.townshipCode),
    index("agri_locations_geography_idx").on(table.geographyLevel, table.stateRegionCode, table.isActive),
  ],
);

export const agriCropLocations = sqliteTable(
  "agri_crop_locations",
  {
    cropLocationId: text("crop_location_id").primaryKey(),
    locationId: text("location_id").notNull(),
    cropId: text("crop_id").notNull(),
    presenceStatus: text("presence_status").notNull(),
    importanceLevel: text("importance_level").notNull(),
    evidenceGeography: text("evidence_geography"),
    evidenceYear: integer("evidence_year"),
    sourceId: text("source_id"),
    confidenceGrade: text("confidence_grade").notNull().default("UNKNOWN"),
    cultivatedArea: text("cultivated_area"),
    cultivatedAreaUnit: text("cultivated_area_unit"),
    cultivatedAreaYear: integer("cultivated_area_year"),
    localVerified: integer("local_verified", { mode: "boolean" }).notNull().default(false),
    verifiedBy: text("verified_by"),
    verifiedAt: text("verified_at"),
    notes: text("notes"),
    createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
    createdBy: text("created_by").notNull(),
    updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`),
    updatedBy: text("updated_by").notNull(),
  },
  (table) => [
    uniqueIndex("agri_crop_locations_scope_unique").on(table.locationId, table.cropId),
    index("agri_crop_locations_presence_idx").on(table.locationId, table.presenceStatus, table.confidenceGrade),
  ],
);

export const agriCropStatistics = sqliteTable(
  "agri_crop_statistics",
  {
    statisticId: text("statistic_id").primaryKey(),
    locationId: text("location_id").notNull(),
    cropId: text("crop_id").notNull(),
    cropYear: integer("crop_year"),
    seasonCode: text("season_code"),
    cultivatedArea: real("cultivated_area"),
    areaUnit: text("area_unit"),
    sownArea: real("sown_area"),
    sownAreaUnit: text("sown_area_unit"),
    harvestedArea: real("harvested_area"),
    harvestedAreaUnit: text("harvested_area_unit"),
    production: real("production"),
    productionUnit: text("production_unit"),
    yieldValue: real("yield"),
    yieldUnit: text("yield_unit"),
    sourceId: text("source_id").notNull(),
    sourceTable: text("source_table"),
    sourceCropName: text("source_crop_name"),
    sourceGeography: text("source_geography").notNull(),
    geographyLevel: text("geography_level").notNull().default("TOWNSHIP"),
    sourceYear: integer("source_year"),
    recordType: text("record_type").notNull().default("ACTUAL"),
    valueQualifier: text("value_qualifier").notNull().default("EXACT"),
    verificationStatus: text("verification_status").notNull().default("UNKNOWN"),
    confidenceScore: integer("confidence_score"),
    notes: text("notes"),
    createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
    createdBy: text("created_by").notNull(),
    updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`),
    updatedBy: text("updated_by").notNull(),
  },
  (table) => [
    index("agri_crop_statistics_location_crop_year_idx").on(table.locationId, table.cropId, table.cropYear, table.seasonCode),
    index("agri_crop_statistics_scope_idx").on(table.sourceGeography, table.recordType, table.valueQualifier, table.verificationStatus),
    index("agri_crop_statistics_geography_idx").on(table.geographyLevel, table.locationId, table.cropYear, table.cropId),
  ],
);

export const agriCropVarieties = sqliteTable(
  "agri_crop_varieties",
  {
    varietyId: text("variety_id").primaryKey(),
    cropId: text("crop_id").notNull(),
    canonicalName: text("canonical_name").notNull(),
    alternateNames: text("alternate_names").notNull().default("[]"),
    localName: text("local_name"),
    countryCode: text("country_code"),
    notes: text("notes"),
    sourceId: text("source_id").notNull(),
    isActive: integer("is_active", { mode: "boolean" }).notNull().default(true),
    createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
    createdBy: text("created_by").notNull(),
    updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`),
    updatedBy: text("updated_by").notNull(),
  },
  (table) => [
    uniqueIndex("agri_crop_varieties_crop_name_unique").on(table.cropId, table.canonicalName),
    index("agri_crop_varieties_active_idx").on(table.cropId, table.isActive),
  ],
);

export const agriLocationCropVarieties = sqliteTable(
  "agri_location_crop_varieties",
  {
    locationCropVarietyId: text("location_crop_variety_id").primaryKey(),
    locationId: text("location_id").notNull(),
    cropId: text("crop_id").notNull(),
    varietyId: text("variety_id").notNull(),
    seasonCode: text("season_code"),
    evidenceYear: integer("evidence_year"),
    sourceId: text("source_id").notNull(),
    verificationStatus: text("verification_status").notNull().default("UNKNOWN"),
    confidenceScore: integer("confidence_score"),
    createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
    createdBy: text("created_by").notNull(),
    updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`),
    updatedBy: text("updated_by").notNull(),
  },
  (table) => [
    uniqueIndex("agri_location_crop_varieties_scope_unique").on(table.locationId, table.cropId, table.varietyId, table.seasonCode, table.evidenceYear),
    index("agri_location_crop_varieties_location_idx").on(table.locationId, table.cropId, table.verificationStatus),
  ],
);

export const agriHistoricalHazards = sqliteTable(
  "agri_historical_hazards",
  {
    hazardId: text("hazard_id").primaryKey(),
    locationId: text("location_id").notNull(),
    hazardType: text("hazard_type").notNull(),
    eventStart: text("event_start"),
    eventEnd: text("event_end"),
    eventYear: integer("event_year"),
    severity: text("severity"),
    affectedArea: real("affected_area"),
    affectedAreaUnit: text("affected_area_unit"),
    description: text("description"),
    sourceId: text("source_id").notNull(),
    verificationStatus: text("verification_status").notNull().default("UNKNOWN"),
    confidenceScore: integer("confidence_score"),
    createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
    createdBy: text("created_by").notNull(),
    updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`),
    updatedBy: text("updated_by").notNull(),
  },
  (table) => [
    index("agri_historical_hazards_location_year_idx").on(table.locationId, table.eventYear, table.hazardType),
    index("agri_historical_hazards_verification_idx").on(table.verificationStatus, table.confidenceScore),
  ],
);

export const agriSources = sqliteTable(
  "agri_sources",
  {
    sourceId: text("source_id").primaryKey(),
    sourceName: text("source_name").notNull(),
    sourceType: text("source_type").notNull(),
    publisher: text("publisher"),
    publicationDate: text("publication_date"),
    sourceGeography: text("source_geography"),
    sourceTable: text("source_table"),
    referenceUri: text("reference_uri"),
    reliabilityGrade: text("reliability_grade").notNull().default("UNKNOWN"),
    notes: text("notes"),
    createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
    createdBy: text("created_by").notNull(),
    updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`),
    updatedBy: text("updated_by").notNull(),
  },
  (table) => [index("agri_sources_geography_idx").on(table.sourceGeography, table.publicationDate)],
);

export const agriLocationContexts = sqliteTable(
  "agri_location_contexts",
  {
    contextId: text("context_id").primaryKey(),
    locationId: text("location_id").notNull(),
    contextType: text("context_type").notNull(),
    contextGeography: text("context_geography").notNull(),
    contextSubject: text("context_subject").notNull(),
    evidenceYear: integer("evidence_year"),
    sourceId: text("source_id").notNull(),
    verificationStatus: text("verification_status").notNull().default("UNKNOWN"),
    confidenceScore: integer("confidence_score"),
    notes: text("notes"),
    createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
    createdBy: text("created_by").notNull(),
    updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`),
    updatedBy: text("updated_by").notNull(),
  },
  (table) => [
    uniqueIndex("agri_location_contexts_scope_unique").on(table.locationId, table.contextType, table.contextSubject, table.sourceId),
    index("agri_location_contexts_location_idx").on(table.locationId, table.contextGeography, table.contextType, table.verificationStatus),
  ],
);

export const agriDataGaps = sqliteTable(
  "agri_data_gaps",
  {
    gapId: text("gap_id").primaryKey(),
    locationId: text("location_id").notNull(),
    cropId: text("crop_id"),
    gapType: text("gap_type").notNull(),
    priority: text("priority").notNull(),
    requiredGeography: text("required_geography").notNull(),
    latestSourceYear: integer("latest_source_year"),
    notes: text("notes"),
    status: text("status").notNull().default("OPEN"),
    createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
    createdBy: text("created_by").notNull(),
    updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`),
    updatedBy: text("updated_by").notNull(),
  },
  (table) => [
    uniqueIndex("agri_data_gaps_scope_unique").on(table.locationId, table.cropId, table.gapType, table.requiredGeography),
    index("agri_data_gaps_status_priority_idx").on(table.status, table.priority, table.locationId),
  ],
);

export const agriCropCalendars = sqliteTable(
  "agri_crop_calendars",
  {
    calendarRecordId: text("calendar_record_id").primaryKey(),
    locationId: text("location_id").notNull(),
    cropId: text("crop_id").notNull(),
    seasonId: text("season_id"),
    cropYear: integer("crop_year"),
    stageCode: text("stage_code").notNull(),
    baselineStartDate: text("baseline_start_date"),
    baselineEndDate: text("baseline_end_date"),
    calendarPrecision: text("calendar_precision").notNull().default("MONTH"),
    windowStartMonth: integer("window_start_month"),
    windowEndMonth: integer("window_end_month"),
    durationDaysMin: integer("duration_days_min"),
    durationDaysMax: integer("duration_days_max"),
    validFromYear: integer("valid_from_year"),
    validToYear: integer("valid_to_year"),
    notes: text("notes"),
    calendarType: text("calendar_type").notNull().default("AUTHORITATIVE_BASELINE"),
    sourceGeography: text("source_geography"),
    sourceId: text("source_id"),
    sourcePublicationDate: text("source_publication_date"),
    verificationLevel: text("verification_level").notNull().default("V0"),
    confidenceScore: integer("confidence_score"),
    inheritedFromLocationId: text("inherited_from_location_id"),
    weatherAdjusted: integer("weather_adjusted", { mode: "boolean" }).notNull().default(false),
    calendarShiftStatus: text("calendar_shift_status").notNull().default("UNKNOWN"),
    calendarShiftDays: integer("calendar_shift_days"),
    localVerified: integer("local_verified", { mode: "boolean" }).notNull().default(false),
    verifiedBy: text("verified_by"),
    verifiedAt: text("verified_at"),
    createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
    createdBy: text("created_by").notNull(),
    updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`),
    updatedBy: text("updated_by").notNull(),
  },
  (table) => [
    index("agri_crop_calendars_location_year_idx").on(table.locationId, table.cropYear, table.cropId),
    index("agri_crop_calendars_scope_idx").on(table.calendarType, table.sourceGeography, table.cropId, table.seasonId),
    index("agri_crop_calendars_verification_idx").on(table.verificationLevel, table.confidenceScore),
  ],
);

export const agriCalendarEstimates = sqliteTable(
  "agri_calendar_estimates",
  {
    estimateId: text("estimate_id").primaryKey(),
    calendarRecordId: text("calendar_record_id").notNull(),
    estimatedStartDate: text("estimated_start_date"),
    estimatedEndDate: text("estimated_end_date"),
    sourceGeography: text("source_geography"),
    sourceId: text("source_id"),
    sourcePublicationDate: text("source_publication_date"),
    verificationLevel: text("verification_level").notNull().default("V0"),
    confidenceScore: integer("confidence_score"),
    weatherAdjusted: integer("weather_adjusted", { mode: "boolean" }).notNull().default(false),
    calendarShiftStatus: text("calendar_shift_status").notNull().default("UNKNOWN"),
    calendarShiftDays: integer("calendar_shift_days"),
    notes: text("notes"),
    createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
    createdBy: text("created_by").notNull(),
    updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`),
    updatedBy: text("updated_by").notNull(),
  },
  (table) => [index("agri_calendar_estimates_calendar_idx").on(table.calendarRecordId, table.verificationLevel)],
);

export const agriCalendarAdjustments = sqliteTable(
  "agri_calendar_adjustments",
  {
    adjustmentId: text("adjustment_id").primaryKey(),
    calendarRecordId: text("calendar_record_id").notNull(),
    weatherStateId: text("weather_state_id"),
    adjustmentStatus: text("adjustment_status").notNull().default("UNKNOWN"),
    shiftDays: integer("shift_days"),
    reasonCodes: text("reason_codes").notNull().default("[]"),
    sourceId: text("source_id"),
    modelVersion: text("model_version"),
    appliedAt: text("applied_at"),
    createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
    createdBy: text("created_by").notNull(),
    updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`),
    updatedBy: text("updated_by").notNull(),
  },
  (table) => [index("agri_calendar_adjustments_calendar_idx").on(table.calendarRecordId, table.adjustmentStatus)],
);

export const agriFieldVerifications = sqliteTable(
  "agri_field_verifications",
  {
    verificationId: text("verification_id").primaryKey(),
    companyId: text("company_id").notNull(),
    locationId: text("location_id").notNull(),
    cropId: text("crop_id"),
    cropYear: integer("crop_year"),
    seasonCode: text("season_code"),
    cropPresence: text("crop_presence").notNull().default("UNKNOWN"),
    importance: text("importance").notNull().default("UNKNOWN"),
    estimatedArea: real("estimated_area"),
    areaUnit: text("area_unit"),
    areaQuality: text("area_quality").notNull().default("UNKNOWN"),
    plantingStartMonth: integer("planting_start_month"),
    plantingEndMonth: integer("planting_end_month"),
    harvestStartMonth: integer("harvest_start_month"),
    harvestEndMonth: integer("harvest_end_month"),
    currentStage: text("current_stage"),
    irrigationType: text("irrigation_type").notNull().default("UNKNOWN"),
    mechanizationLevel: text("mechanization_level").notNull().default("UNKNOWN"),
    commonMachines: text("common_machines").notNull().default("[]"),
    notes: text("notes"),
    fieldName: text("field_name").notNull(),
    proposedValue: text("proposed_value").notNull(),
    verificationLevel: text("verification_level").notNull().default("V2"),
    evidence: text("evidence").notNull(),
    verifiedRole: text("verified_role"),
    verificationMethod: text("verification_method").notNull().default("OTHER"),
    confidenceScore: integer("confidence_score"),
    sourceId: text("source_id"),
    verifiedBy: text("verified_by").notNull(),
    verifiedAt: text("verified_at").notNull().default(sql`CURRENT_TIMESTAMP`),
    status: text("status").notNull().default("PENDING"),
    reviewedBy: text("reviewed_by"),
    reviewedAt: text("reviewed_at"),
    createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
    createdBy: text("created_by").notNull(),
    updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`),
    updatedBy: text("updated_by").notNull(),
  },
  (table) => [
    index("agri_field_verifications_company_idx").on(table.companyId, table.status, table.verifiedAt),
    index("agri_field_verifications_location_idx").on(table.locationId, table.cropId, table.fieldName),
    index("agri_field_verifications_current_idx").on(table.locationId, table.cropId, table.verificationLevel, table.status, table.verifiedAt),
  ],
);

export const agriCropWeatherRules = sqliteTable(
  "agri_crop_weather_rules",
  {
    ruleId: text("rule_id").primaryKey(),
    cropId: text("crop_id").notNull(),
    stageCode: text("stage_code").notNull(),
    weatherVariable: text("weather_variable").notNull(),
    ruleType: text("rule_type").notNull(),
    warningMin: text("warning_min"),
    warningMax: text("warning_max"),
    criticalMin: text("critical_min"),
    criticalMax: text("critical_max"),
    unit: text("unit"),
    riskType: text("risk_type"),
    direction: text("direction"),
    sourceId: text("source_id"),
    sourceGeography: text("source_geography"),
    sourceVersion: text("source_version"),
    confidenceGrade: text("confidence_grade").notNull().default("UNKNOWN"),
    localCalibrated: integer("local_calibrated", { mode: "boolean" }).notNull().default(false),
    calibrationLocation: text("calibration_location"),
    calibrationYear: integer("calibration_year"),
    isActive: integer("is_active", { mode: "boolean" }).notNull().default(true),
    createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
    createdBy: text("created_by").notNull(),
    updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`),
    updatedBy: text("updated_by").notNull(),
  },
  (table) => [index("agri_crop_weather_rules_lookup_idx").on(table.cropId, table.stageCode, table.weatherVariable, table.isActive)],
);

export const agriCropWeatherState = sqliteTable(
  "agri_crop_weather_state",
  {
    stateId: text("state_id").primaryKey(),
    locationId: text("location_id").notNull(),
    cropId: text("crop_id").notNull(),
    stageCode: text("stage_code").notNull(),
    weatherVariable: text("weather_variable").notNull(),
    observedValue: text("observed_value"),
    unit: text("unit"),
    riskType: text("risk_type"),
    stateStatus: text("state_status").notNull().default("UNKNOWN"),
    source: text("source"),
    provider: text("provider"),
    retrievedAt: text("retrieved_at"),
    qualityStatus: text("quality_status").notNull().default("UNKNOWN"),
    calculatedAt: text("calculated_at"),
    reasonCodes: text("reason_codes").notNull().default("[]"),
    createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
    createdBy: text("created_by").notNull(),
    updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`),
    updatedBy: text("updated_by").notNull(),
  },
  (table) => [index("agri_crop_weather_state_lookup_idx").on(table.locationId, table.cropId, table.stageCode, table.weatherVariable)],
);

export const weatherClimatology = sqliteTable(
  "weather_climatology",
  {
    climatologyId: text("climatology_id").primaryKey(),
    locationId: text("location_id").notNull(),
    variable: text("variable").notNull(),
    periodStartMonth: integer("period_start_month"),
    periodEndMonth: integer("period_end_month"),
    normalValue: text("normal_value"),
    unit: text("unit"),
    sourceId: text("source_id"),
    sourceGeography: text("source_geography"),
    sourceYear: integer("source_year"),
    confidenceGrade: text("confidence_grade").notNull().default("UNKNOWN"),
    createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
    createdBy: text("created_by").notNull(),
    updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`),
    updatedBy: text("updated_by").notNull(),
  },
  (table) => [index("weather_climatology_lookup_idx").on(table.locationId, table.variable, table.sourceYear)],
);

export const weatherAnomalies = sqliteTable(
  "weather_anomalies",
  {
    anomalyId: text("anomaly_id").primaryKey(),
    locationId: text("location_id").notNull(),
    variable: text("variable").notNull(),
    periodStart: text("period_start"),
    periodEnd: text("period_end"),
    observedValue: text("observed_value"),
    normalValue: text("normal_value"),
    anomalyValue: text("anomaly_value"),
    unit: text("unit"),
    sourceId: text("source_id"),
    confidenceGrade: text("confidence_grade").notNull().default("UNKNOWN"),
    calculatedAt: text("calculated_at"),
    createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
    createdBy: text("created_by").notNull(),
    updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`),
    updatedBy: text("updated_by").notNull(),
  },
  (table) => [index("weather_anomalies_lookup_idx").on(table.locationId, table.variable, table.periodEnd)],
);

export const agriServiceProviders = sqliteTable(
  "agri_service_providers",
  {
    providerId: text("provider_id").primaryKey(),
    companyId: text("company_id").notNull(),
    providerType: text("provider_type").notNull(),
    locationId: text("location_id"),
    serviceArea: text("service_area"),
    machineType: text("machine_type"),
    brand: text("brand"),
    model: text("model"),
    machineCount: integer("machine_count"),
    primaryCrop: text("primary_crop"),
    customerId: text("customer_id"),
    salespersonId: text("salesperson_id"),
    lastVerified: text("last_verified"),
    status: text("status").notNull().default("UNKNOWN"),
    createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
    createdBy: text("created_by").notNull(),
    updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`),
    updatedBy: text("updated_by").notNull(),
  },
  (table) => [index("agri_service_providers_company_idx").on(table.companyId, table.locationId, table.providerType, table.status)],
);

export const agriOpportunities = sqliteTable(
  "agri_opportunities",
  {
    opportunityId: text("opportunity_id").primaryKey(),
    companyId: text("company_id").notNull(),
    locationId: text("location_id"),
    cropId: text("crop_id"),
    seasonId: text("season_id"),
    stageCode: text("stage_code"),
    opportunityType: text("opportunity_type").notNull(),
    machineCategory: text("machine_category"),
    productId: text("product_id"),
    customerId: text("customer_id"),
    serviceProviderId: text("service_provider_id"),
    salespersonId: text("salesperson_id"),
    salesTerritoryId: text("sales_territory_id"),
    opportunityScore: integer("opportunity_score"),
    confidenceScore: integer("confidence_score"),
    priorityScore: integer("priority_score"),
    daysToWindow: integer("days_to_window"),
    windowStart: text("window_start"),
    windowEnd: text("window_end"),
    weatherRiskScore: integer("weather_risk_score"),
    weatherSuitabilityScore: integer("weather_suitability_score"),
    reasonCodes: text("reason_codes").notNull().default("[]"),
    recommendedAction: text("recommended_action"),
    modelVersion: text("model_version").notNull(),
    status: text("status").notNull().default("ACTIVE"),
    createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
    updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`),
    expiresAt: text("expires_at"),
    createdBy: text("created_by").notNull(),
    updatedBy: text("updated_by").notNull(),
  },
  (table) => [
    index("agri_opportunities_company_status_idx").on(table.companyId, table.status, table.priorityScore),
    index("agri_opportunities_company_filter_idx").on(table.companyId, table.locationId, table.cropId, table.salespersonId, table.confidenceScore),
  ],
);
