import type { Language } from "../../locales";
import type { AgricultureTrendMetric } from "./agriculture.types";

export function localizedText(language: Language, thai: string, english: string) {
  return language === "th" ? thai : english;
}

export function agricultureCopy(language: Language) {
  const text = (thai: string, english: string) => localizedText(language, thai, english);
  return {
    common: {
      noData: text("ไม่มีข้อมูล", "No Data"),
      notAvailable: text("ไม่มีข้อมูล", "N/A"),
      unknown: text("ยังไม่มีข้อมูลยืนยัน", "Unknown"),
      sourceNA: text("ไม่ระบุแหล่งข้อมูล", "Source N/A"),
      geographyNA: text("ไม่ระบุระดับพื้นที่", "Geography N/A"),
      yearNA: text("ไม่ระบุปี", "Year N/A"),
      seasonNA: text("ไม่ระบุฤดูกาล", "Season N/A"),
      locationNA: text("ไม่ระบุพื้นที่", "Unknown location"),
      cropNA: text("ไม่ระบุชนิดพืช", "Crop N/A"),
      needsVerification: text("รอตรวจสอบ", "Needs Verification"),
      tryAgain: text("ลองอีกครั้ง", "Try again"),
      loading: text("กำลังโหลด…", "Loading…"),
      refresh: text("โหลดข้อมูลใหม่", "Refresh"),
      refreshing: text("กำลังโหลดข้อมูลใหม่…", "Refreshing…"),
      save: text("บันทึกข้อมูลยืนยันจากพื้นที่", "Save local verification"),
      saving: text("กำลังบันทึก…", "Saving…"),
      openForm: text("เปิดแบบฟอร์ม", "Open form"),
      hideForm: text("ซ่อนแบบฟอร์ม", "Hide form"),
      addDetails: text("เพิ่มรายละเอียด", "Add details"),
    },
    tabs: {
      overview: text("ภาพรวม", "Overview"),
      weather: text("สภาพอากาศ", "Weather"),
      agriculture: text("ข้อมูลเกษตร", "Agriculture"),
      calendar: text("ปฏิทินการเพาะปลูก", "Calendar"),
      opportunities: text("โอกาสทางการขาย", "Opportunities"),
    },
      top: {
      weatherUpdated: text("อัปเดตสภาพอากาศ", "Weather update"),
      weatherUnavailable: text("ไม่พบข้อมูลอัปเดตสภาพอากาศ", "Weather update unavailable"),
      agriculture: text("ข้อมูลเกษตร", "Agriculture"),
      weatherAgricultureUnavailable: text("ไม่สามารถใช้งานข้อมูลสภาพอากาศและเกษตรกรรมได้", "Weather & Agriculture is unavailable"),
      loadingData: text("กำลังโหลดข้อมูลสภาพอากาศและเกษตรกรรม…", "Loading Weather & Agriculture data…"),
      loadingDataHelp: text("กำลังตรวจสอบข้อมูลพื้นที่จาก D1 ที่ได้รับอนุญาตและชั้นข้อมูลสภาพอากาศสดที่ใช้ร่วมกัน", "Checking authorized local D1 records and the shared live weather layer."),
      sectionsAria: text("ส่วนข้อมูลสภาพอากาศและเกษตรกรรม", "Weather and Agriculture sections"),
    },
    filters: {
      aria: text("ตัวกรองข้อมูลเกษตร", "Agriculture filters"),
      title: text("ขอบเขตการวางแผน", "Planning scope"),
      description: text("แยกระดับพื้นที่ให้ชัดเจน: ข้อมูลอ้างอิงระดับรัฐไม่ถูกนำมาใช้แทนข้อมูลจริงระดับ Township", "Geography stays explicit: state baselines never become township actuals."),
      geography: text("ระดับพื้นที่", "Geography"),
      allGeographies: text("ทุกระดับพื้นที่", "All geographies"),
      stateRegion: text("รัฐ/ภูมิภาค", "State / Region"),
      regional: text("ระดับภูมิภาค", "Regional"),
      township: text("Township (เขตการปกครอง)", "Township"),
      location: text("พื้นที่", "Location"),
      allLocations: text("ทุกพื้นที่", "All locations"),
      crop: text("ชนิดพืช", "Crop"),
      allCrops: text("ทุกชนิดพืช", "All crops"),
      yearFrom: text("ตั้งแต่ปี", "Year from"),
      allYearsFrom: text("ทุกปีตั้งแต่", "All years from"),
      yearTo: text("ถึงปี", "Year to"),
      allYearsTo: text("ทุกปีจนถึง", "All years to"),
      historicalTrendMetric: text("ตัวชี้วัดแนวโน้มย้อนหลัง", "Historical trend metric"),
      sownAreaTrend: text("แนวโน้มพื้นที่ปลูก", "Sown Area Trend"),
      harvestedAreaTrend: text("แนวโน้มพื้นที่เก็บเกี่ยวแล้ว", "Harvested Area Trend"),
      productionTrend: text("แนวโน้มผลผลิต", "Production Trend"),
    },
    overview: {
      keyPerformanceIndicators: text("ตัวชี้วัดสำคัญด้านเกษตร", "Agriculture key performance indicators"),
      activeCrops: text("พืชที่ปลูก", "Active Crops"),
      cultivatedArea: text("พื้นที่เพาะปลูก", "Cultivated Area"),
      sownArea: text("พื้นที่ปลูก", "Sown Area"),
      harvestedArea: text("พื้นที่เก็บเกี่ยวแล้ว", "Harvested Area"),
      production: text("ผลผลิต", "Production"),
      harvestSeason: text("ช่วงเก็บเกี่ยว", "Harvest Season"),
      dataCoverage: text("ความครอบคลุมของข้อมูล", "Data Coverage"),
      dataConfidence: text("ความน่าเชื่อถือของข้อมูล", "Data Confidence"),
      awaitingVerifiedPresence: text("รอการยืนยันว่าพบพืชในพื้นที่", "Awaiting verified crop presence"),
      stateRegionActual: text("ข้อมูลจริงระดับรัฐ/ภูมิภาค", "State/Region actual records"),
      verifiedLocationRecords: text("จากข้อมูลพื้นที่ที่ยืนยันแล้ว", "From verified location records"),
      noSourceValue: text("ไม่มีค่าจากแหล่งข้อมูล", "No source value"),
      stateRegionCso: text("ข้อมูลจริงระดับรัฐ/ภูมิภาค · CSO 9.12", "State/Region actual · CSO 9.12"),
      noActualArea: text("ไม่มีข้อมูลพื้นที่จริงในขอบเขตที่เลือก", "No actual area in scope"),
      actualTownshipOnly: text("เฉพาะข้อมูลจริงระดับ Township", "Actual township records only"),
      sourceValuesOnly: text("แสดงเฉพาะค่าที่มีแหล่งข้อมูล", "Source values only"),
      noVerifiedHarvestWindow: text("ยังไม่มีช่วงเก็บเกี่ยวที่ยืนยันแล้ว", "No verified harvest window"),
      historicalSourceBound: text("ข้อมูลย้อนหลังตามแหล่งอ้างอิง", "Historical / source-bound"),
      sourceBackedYearsCrops: text("ปีและชนิดพืชที่มีแหล่งข้อมูลรองรับ", "Source-backed years and crops"),
      noVerifiedStateRegion: text("ยังไม่มีข้อมูลรัฐ/ภูมิภาคที่ยืนยันแล้ว", "No verified state/region records"),
      noVerifiedAgricultureSource: text("ยังไม่มีแหล่งข้อมูลเกษตรที่ยืนยันแล้ว", "No verified agriculture source"),
      deterministicSourceRecords: text("คำนวณตามข้อมูลจากแหล่งอ้างอิงอย่างเป็นระบบ", "Deterministic from source records"),
      situationAndWeather: text("ภาพรวมพื้นที่และสภาพอากาศของพืช", "Agriculture situation and crop weather"),
      summarySectionsAria: text("สรุปสภาพอากาศ ปฏิทินการเพาะปลูก และข้อมูลวิเคราะห์จาก KAI", "Weather snapshot, agricultural calendar, and KAI insight"),
      mapTitle: text("แผนที่สถานการณ์เมียนมาและตาก", "Myanmar & Tak Situation Map"),
      mapDescription: text("แสดงจุดสภาพอากาศสดร่วมกับข้อมูลเกษตร เฉพาะพื้นที่ที่มีการยืนยันจากพื้นที่แล้ว", "Live weather points are shown alongside agriculture records only when locally verified."),
      mapUnavailable: text("ไม่พบแผนที่สภาพอากาศ", "Weather map unavailable"),
      mapUnavailableMessage: text("ผู้ให้บริการสภาพอากาศสดไม่ส่งข้อมูลที่ใช้งานได้กลับมา", "The shared live weather provider did not return a usable snapshot."),
      canonicalPilotLocations: text("พื้นที่นำร่องตามรายการมาตรฐาน", "canonical pilot locations"),
      noCanonicalLocations: text("ไม่มีพื้นที่มาตรฐาน", "No canonical locations"),
      cropPresenceUnknown: text("ข้อมูลการมีอยู่ของพืชยังเป็นสถานะไม่ยืนยันจนกว่าจะตรวจสอบ", "crop presence remains Unknown until verified."),
      currentCropWeather: text("พืชปัจจุบันและสภาพอากาศ", "Current Crop & Weather"),
      verificationPending: text("รอการยืนยันข้อมูล", "Verification pending"),
      unknownLocation: text("ไม่ระบุพื้นที่", "Unknown location"),
      regionNA: text("ไม่ระบุภูมิภาค", "Region N/A"),
      countryNA: text("ไม่ระบุประเทศ", "Country N/A"),
      highWeatherSignal: text("สัญญาณสภาพอากาศสูง", "High weather signal"),
      watchWeather: text("ควรเฝ้าระวังสภาพอากาศ", "Watch weather"),
      normalWeather: text("สภาพอากาศปกติ", "Normal weather"),
      mainCrop: text("พืชหลัก", "Main crop"),
      currentStage: text("ระยะพืชปัจจุบัน", "Current stage"),
      harvestWindow: text("ช่วงเก็บเกี่ยว", "Harvest window"),
      currentEstimate: text("ประมาณการปัจจุบัน", "Current estimate"),
      opportunity: text("โอกาสทางการขาย", "Opportunity"),
      confidence: text("ความน่าเชื่อถือ", "Confidence"),
      salesTerritory: text("พื้นที่รับผิดชอบการขาย", "Sales territory"),
      weatherAvailableHelp: text("มีข้อมูลสภาพอากาศสด แต่ยังไม่นำไปแปลงเป็นความเสี่ยงของพืช เพราะยังไม่มีระยะพืชที่ยืนยันแล้วหรือเกณฑ์ทางการเกษตรที่กำหนดไว้", "Live weather is available. It is not being converted into crop risk because no verified crop stage or agronomic threshold exists."),
      weatherUnavailableHelp: text("ไม่มีข้อมูลสภาพอากาศร่วมสำหรับพื้นที่มาตรฐานนี้", "No shared weather record is available for this canonical location."),
      noCurrentWeather: text("ยังไม่มีสภาพอากาศปัจจุบัน", "No current weather"),
      selectLocationWeather: text("เลือกพื้นที่หลังจากชั้นข้อมูลสภาพอากาศร่วมพร้อมใช้งาน", "Select a location after the shared weather layer is available."),
      coverageHelp: text("คำนวณจากข้อมูลใน D1 ของพื้นที่ ส่วนข้อมูลประกอบจะไม่ถูกนับเป็นตัวชี้วัดหลัก", "Coverage is calculated from local D1 records; context is not KPI data."),
      factualCropPresence: text("พื้นที่ที่มีข้อมูลยืนยันการพบพืช", "Factual crop presence"),
      townshipsWithArea: text("Township ที่มีข้อมูลพื้นที่", "Townships with area"),
      townshipsWithProduction: text("Township ที่มีข้อมูลผลผลิต", "Townships with production"),
      townshipsWithYield: text("Township ที่มีข้อมูลผลผลิตต่อหน่วยพื้นที่", "Townships with yield"),
      townshipsWithCalendar: text("Township ที่มีปฏิทินการเพาะปลูก", "Townships with calendar"),
      stateRegionCalendarBaseline: text("ข้อมูลอ้างอิงปฏิทินระดับรัฐ/ภูมิภาค", "State/region calendar baseline"),
      weatherMapped: text("พื้นที่ที่เชื่อมโยงสภาพอากาศแล้ว", "Weather mapped"),
      targetPlanRecords: text("ข้อมูลเป้าหมาย/แผน", "Target / plan records"),
      noDerivedMetrics: text("ไม่มีการคำนวณผลผลิต ผลผลิตต่อหน่วยพื้นที่ ระยะพืช คะแนนความเสี่ยง หรือคำแนะนำเครื่องจักรจากพื้นที่เพาะปลูก", "No production, yield, crop stage, risk score, or machine recommendation is derived from cultivated area."),
      weatherSnapshot: text("สรุปสภาพอากาศ", "Weather Snapshot"),
      rainfall7d: text("ปริมาณฝน / 7 วัน", "Rainfall / 7d"),
      soilMoisture: text("ความชื้นในดิน", "Soil moisture"),
      floodRisk: text("ความเสี่ยงน้ำท่วม", "Flood risk"),
      droughtRisk: text("ความเสี่ยงภัยแล้ง", "Drought risk"),
      weatherSnapshotHelp: text("ปริมาณฝนเป็นข้อมูลพยากรณ์จากผู้ให้บริการ ส่วนความชื้นในดิน น้ำท่วม ภัยแล้ง และความผิดปกติยังไม่เชื่อมต่อในระยะที่ 1", "Rainfall is provider forecast data. Soil moisture, flood, drought, and anomaly layers are not connected in Phase 1."),
      calendarPreview: text("ปฏิทินการเพาะปลูก", "Agricultural Calendar"),
      calendarPreviewHelp: text("ข้อมูลอ้างอิงและประมาณการปัจจุบันจะแสดงแยกกัน", "Baseline and current estimate stay separate"),
      noVerifiedCalendar: text("ยังไม่มีข้อมูลปฏิทินที่ยืนยันแล้ว", "No verified calendar records"),
      noCalendarForScope: text("ไม่มีข้อมูลอ้างอิงหรือประมาณการปัจจุบันสำหรับขอบเขตที่เลือก", "No baseline or current estimate is available for the selected scope."),
      kaiInsight: text("ข้อมูลวิเคราะห์จาก KAI", "KAI Insight"),
      kaiPaused: text("คำแนะนำด้านเกษตรจาก KAI หยุดไว้ชั่วคราวในรอบนี้ กฎความปลอดภัยเดิมยังคงใช้: ไม่อนุมานระยะพืช วันที่ พื้นที่เพาะปลูก ความเป็นเจ้าของ คะแนน ความน่าเชื่อถือ หรือการเปลี่ยนปฏิทินจากสภาพอากาศ", "KAI Agriculture recommendations are paused in this pass. Existing safety rules remain: no inferred crop stage, dates, acreage, ownership, score, confidence, or weather-driven calendar change."),
      suggestedPrompts: text("คำถามแนะนำ", "Suggested prompts"),
      promptVerification: text("พื้นที่นำร่องใดต้องยืนยันข้อมูลพืช?", "Which pilot locations need crop verification?"),
      promptWeatherFields: text("ข้อมูลสภาพอากาศส่วนใดยังไม่มี?", "What weather fields are still unavailable?"),
      promptCalendarChanges: text("แสดงการเปลี่ยนแปลงปฏิทินที่ยืนยันแล้ว", "Show verified calendar changes"),
      pendingReview: text("รายการยืนยันข้อมูลรอตรวจสอบ", "verification record(s) pending review."),
      noVerificationSubmissions: text("ยังไม่มีรายการส่งยืนยันข้อมูล", "No verification submissions yet."),
    },
    data: {
      cropPresence: text("ข้อมูลพืชที่ปลูก", "Crop Presence"),
      cropPresenceHelp: text("ข้อมูลการพบพืช สถิติ และระยะพืชเป็นคนละรายการกัน ข้อมูลระดับภูมิภาคจะไม่ถูกนำมาเป็นข้อมูลการพบพืชระดับ Township", "Presence, statistics, and stage are separate records. Regional evidence never becomes township presence."),
      location: text("พื้นที่", "Location"),
      crop: text("ชนิดพืช", "Crop"),
      presence: text("สถานะการพบพืช", "Presence"),
      geographyYear: text("ระดับพื้นที่ / ปี", "Geography / year"),
      sourceVerification: text("แหล่งข้อมูล / การยืนยัน", "Source / verification"),
      noTownshipStats: text("ยังไม่มีสถิติพืชระดับ Township ที่ยืนยันแล้ว", "No township-level crop statistics verified yet"),
      contextAvailable: text("มีข้อมูลจากแหล่งประวัติศาสตร์/การปกครองหรือบริบทระดับภูมิภาคด้านล่าง แต่ไม่ถือเป็นข้อเท็จจริงปัจจุบันของพืช", "Historical/Admin sources or regional context are available below; they do not create current crop facts."),
      unknownCropRecords: text("รายการพื้นที่-พืชที่ระบุว่ายังไม่มีข้อมูลยืนยัน", "crop-location records are explicitly marked UNKNOWN."),
      noCropRecords: text("ไม่มีรายการพื้นที่-พืช", "No crop-location records are available."),
      verificationStatus: text("สถานะการยืนยันข้อมูล", "Verification status"),
      pilotLocations: text("พื้นที่นำร่อง", "Pilot locations"),
      cropMaster: text("รายการพืชมาตรฐาน", "Crop master"),
      verifiedCropRecords: text("รายการพืชที่ยืนยันแล้ว", "Verified crop records"),
      townshipStatistics: text("สถิติระดับ Township", "Township statistics"),
      varieties: text("พันธุ์พืช", "Varieties"),
      historicalHazards: text("เหตุการณ์เสี่ยงย้อนหลัง", "Historical hazards"),
      stageProductionYieldUnavailable: text("ระยะพืชปัจจุบัน ผลผลิต ผลผลิตต่อหน่วยพื้นที่ และผลกระทบต่อพืชจะแสดงเมื่อมีแหล่งข้อมูลแยกต่างหากเท่านั้น", "Current stage, production, yield, and crop impact remain unavailable unless separately sourced."),
      historicalRegionalContext: text("บริบทประวัติศาสตร์/ภูมิภาค", "Historical / Regional Context"),
      noHistoricalRegionalContext: text("ไม่มีบริบทประวัติศาสตร์หรือภูมิภาค", "No historical or regional context"),
      contextSeparate: text("ข้อมูลบริบทจะแสดงแยกต่างหากและไม่ถูกนำไปคำนวณตัวชี้วัดพืช", "Context records are shown separately and never enter crop KPIs."),
      openDataGaps: text("ประเด็นข้อมูลที่ยังขาด", "Open Data Gaps"),
      noOpenDataGaps: text("ไม่มีประเด็นข้อมูลที่เปิดอยู่", "No open data gaps"),
      gapsSeparate: text("ข้อมูลประเด็นที่ขาดเป็นข้อมูลประกอบ แยกจากข้อเท็จจริงด้านเกษตรและการคำนวณตัวชี้วัด", "Gap metadata is separate from agriculture facts and KPI calculations."),
      historicalStatistics: text("สถิติย้อนหลัง", "Historical Statistics"),
      historicalStatisticsHelp: text("แยกข้อมูลจริง เป้าหมาย และแผนออกจากกัน โดยเฉพาะข้อมูลจริงระดับ Township ที่ผ่านเกณฑ์เท่านั้นจึงจะนำไปคำนวณพื้นที่", "ACTUAL, TARGET, and PLAN are visible separately; only eligible ACTUAL township records feed the area KPI."),
      records: text("รายการ", "records"),
      locationCrop: text("พื้นที่ / ชนิดพืช", "Location / crop"),
      area: text("พื้นที่", "Area"),
      yearSeason: text("ปี / ฤดูกาล", "Year / season"),
      recordType: text("ประเภทข้อมูล", "Record"),
      geography: text("ระดับพื้นที่", "Geography"),
      source: text("แหล่งข้อมูล", "Source"),
      verification: text("การยืนยันข้อมูล", "Verification"),
      noHistoricalTownshipStats: text("ไม่มีสถิติย้อนหลังระดับ Township", "No historical township statistics"),
      noTownshipSourceRecord: text("ไม่มีข้อมูลพื้นที่ ผลผลิต หรือผลผลิตต่อหน่วยพื้นที่ หากไม่มีรายการแหล่งข้อมูลระดับ Township", "Area, production, and yield are not inferred when no township source record exists."),
      cropVarieties: text("พันธุ์พืช", "Crop Varieties"),
      noVerifiedVarieties: text("ไม่มีพันธุ์พืชที่ยืนยันแล้ว", "No verified varieties"),
      varietiesRequireEvidence: text("รายการพันธุ์พืชต้องมีหลักฐานจากแหล่งข้อมูลของพื้นที่ และจะไม่แบ่งพื้นที่เพาะปลูกตามพันธุ์พืช", "Variety records require source-backed location evidence; acreage is not split by variety."),
      historicalHazardContext: text("บริบทเหตุการณ์เสี่ยงย้อนหลัง", "Historical Hazard Context"),
      noHistoricalHazards: text("ไม่มีเหตุการณ์เสี่ยงย้อนหลัง", "No historical hazards"),
      hazardSeparate: text("บริบทเหตุการณ์เสี่ยงแยกจากผลกระทบต่อพืช และไม่ทำให้ปฏิทินหรือการคำนวณความเสียหายเปลี่ยนแปลง", "Hazard context is separate from crop impact and does not shift calendars or calculate losses."),
      currentCropStage: text("ระยะพืชปัจจุบัน", "Current Crop Stage"),
      noVerifiedCurrentStage: text("ยังไม่มีระยะพืชปัจจุบันที่ยืนยันแล้ว", "No verified current crop stage"),
      currentStageLocalOnly: text("ระยะพืชปัจจุบันมาจากการยืนยันในพื้นที่เท่านั้น สภาพอากาศและปฏิทินจะไม่ถูกใช้อนุมานระยะพืช", "Current stage is populated only from local field verification; weather and calendar do not infer it."),
      weatherImpact: text("ผลกระทบจากสภาพอากาศ", "Weather Impact"),
      noCalibratedImpact: text("ยังไม่มีผลกระทบสภาพอากาศต่อพืชที่ผ่านการปรับเทียบ", "No calibrated crop-weather impact"),
      weatherSeparate: text("มีข้อมูลสภาพอากาศสดแยกต่างหาก แต่ยังไม่มีสถานะสภาพอากาศต่อพืชที่ผ่านการปรับเทียบ", "Live weather is available separately, but no calibrated crop-weather state is recorded."),
      localYear: text("ข้อมูลจากพื้นที่ ปี", "local"),
      officialYield: text("ผลผลิตต่อหน่วยพื้นที่จากแหล่งทางการ", "Official Yield"),
      nationalBaseline: text("ข้อมูลอ้างอิงระดับประเทศเมียนมา", "MYANMAR NATIONAL BASELINE"),
      officialYieldHelp: text("Myanmar Statistical Yearbook 2024 · ตาราง 9.15 · ผลผลิตต่อเอเคอร์ที่เก็บเกี่ยวแล้วระดับสหภาพ ข้อมูลนี้ไม่ถูกนำไปใช้เป็นผลผลิตจริงของ Bago, Mon, Kayin หรือ Township", "Myanmar Statistical Yearbook 2024 · Table 9.15 · Union-level yield per harvested acre. This benchmark never becomes Bago, Mon, Kayin, or Township actual yield."),
      localYield: text("ผลผลิตต่อหน่วยพื้นที่ในพื้นที่", "Local Yield"),
      available: text("มีข้อมูล", "Available"),
      noStateTownshipYield: text("ไม่มีการคำนวณผลผลิตระดับรัฐหรือ Township", "No state/township yield is derived."),
      subtype: text("ประเภทย่อย", "Subtype"),
      officialYieldColumn: text("ผลผลิตต่อหน่วยพื้นที่จากแหล่งทางการ", "Official yield"),
      union: text("เมียนมา · ระดับสหภาพ", "Myanmar · UNION"),
      table: text("ตาราง", "Table"),
      noOfficialYield: text("ไม่มีข้อมูลผลผลิตต่อหน่วยพื้นที่ระดับสหภาพจากแหล่งทางการ", "No official Union yield"),
      noNationalYield: text("ไม่มีรายการผลผลิตต่อหน่วยพื้นที่ระดับประเทศที่ยืนยันแล้วสำหรับชนิดพืชและปีที่เลือก", "No verified national yield record is available for the selected crop and years."),
      nativeUnits: text("คงหน่วยเดิมตามแหล่งข้อมูล Rain/Winter และ Early/Late และไม่แปลงหน่วยหรือคำนวณผลผลิตระดับพื้นที่", "Native units are preserved exactly as published. Rain/Winter and Early/Late source subtypes remain separate; no conversion or local yield calculation is performed."),
      stateRegionBackbone: text("ฐานข้อมูลสถิติระดับรัฐ/ภูมิภาค", "State/Region Statistical Backbone"),
      stateRegionActual: text("ข้อมูลจริงระดับรัฐ/ภูมิภาค", "STATE/REGION ACTUAL"),
      stateRegionHelp: text("CSO Myanmar Statistical Yearbook 2024 · ตาราง 9.12 · 2019/20–2023/24 เป็นข้อมูลระดับรัฐ/ภูมิภาคเท่านั้น และไม่คัดลอกค่าไปเป็นข้อมูลจริงระดับ Township", "CSO Myanmar Statistical Yearbook 2024 · Table 9.12 · 2019/20–2023/24. These are state/region records only; no value is copied into township actuals."),
      latestSourceYear: text("ปีล่าสุดจากแหล่งข้อมูล", "Latest source year"),
      metric: text("ตัวชี้วัด", "Metric"),
      actualRecords: text("รายการข้อมูลจริง", "actual records"),
      crops: text("ชนิดพืช", "crops"),
      sown: text("พื้นที่ปลูก", "Sown"),
      harvested: text("พื้นที่เก็บเกี่ยวแล้ว", "Harvested"),
      productionShort: text("ผลผลิต", "Production"),
      yieldShort: text("ผลผลิตต่อหน่วยพื้นที่", "Yield"),
      noStateRegionActual: text("ไม่มีข้อมูลจริงระดับรัฐ/ภูมิภาค", "No state/region actual records are available."),
      selectedHistoricalTrend: text("แนวโน้มย้อนหลังที่เลือก", "Selected Historical Trend"),
      cropMixByArea: text("สัดส่วนพืชตามพื้นที่", "Crop Mix by Area"),
      stateRegionComparison: text("เปรียบเทียบรัฐ/ภูมิภาค", "State/Region Comparison"),
      areaVsProduction: text("พื้นที่เทียบกับผลผลิต", "Area vs Production"),
      yieldTrend: text("แนวโน้มผลผลิตต่อหน่วยพื้นที่", "Yield Trend"),
      officialOnly: text("เฉพาะข้อมูลทางการ", "Official only"),
      noUnit: text("ไม่ระบุหน่วย", "No unit"),
      unionLevelYield: text("ตาราง CSO 9.15 เป็นข้อมูลระดับสหภาพ แหล่งข้อมูลนี้ไม่มีผลผลิตต่อหน่วยพื้นที่ระดับรัฐ/ภูมิภาค จึงไม่คำนวณเพิ่ม", "CSO Table 9.15 is Union-level in this source; no state/region yield is derived."),
      provenance: text("ที่มาข้อมูล", "Provenance"),
      rawLabels: text("ชื่อพืชตามแหล่งข้อมูล CSO ยังคงแสดงในแต่ละรายการ", "Raw CSO crop labels remain visible in each record."),
      noDataNeedsVerification: text("ไม่มีข้อมูล · รอตรวจสอบ", "No Data · Needs Verification"),
      yearRangeUnknown: text("ไม่ระบุปี", "Year N/A"),
    },
    calendar: {
      title: text("ปฏิทินการเพาะปลูก", "Agricultural Calendar"),
      help: text("ข้อมูลอ้างอิงจะไม่ถูกแก้ทับ ประมาณการปัจจุบันจะแสดงเฉพาะเมื่อมีการบันทึกและระบุแหล่งข้อมูลแยกต่างหาก", "Baseline is immutable. Current estimates are shown only when separately recorded and sourced."),
      sourceBound: text("มีแหล่งข้อมูลรองรับ", "Source-bound"),
      timelineAria: text("ลำดับเวลาปฏิทินการเพาะปลูก", "Agricultural calendar timeline"),
      cropStage: text("พืช / ระยะ", "Crop / stage"),
      coverageAria: text("ความครอบคลุมของปฏิทิน", "Calendar coverage"),
      townshipCalendar: text("Township ที่มีปฏิทิน", "Townships with township calendar"),
      nationalBaselines: text("ข้อมูลอ้างอิงระดับประเทศ", "National baselines"),
      regionalBaselines: text("ข้อมูลอ้างอิงระดับภูมิภาค", "Regional baselines"),
      stateRegionsBaseline: text("รัฐ/ภูมิภาคที่มีข้อมูลอ้างอิง", "State/regions with baseline"),
      cropsWithBaseline: text("ชนิดพืชที่มีข้อมูลอ้างอิงปฏิทิน", "Crops with calendar baseline"),
      cropsWithoutCalendar: text("ชนิดพืชที่ยังไม่มีปฏิทิน", "Crops without calendar"),
      weatherHelp: text("สภาพอากาศจะไม่แก้ไขวันที่ในข้อมูลอ้างอิง การปรับปฏิทินต้องมีแหล่งข้อมูลที่บันทึกไว้ มีประมาณการแยกต่างหาก มีสถานะที่กำหนดแน่นอน และมีระดับการยืนยันข้อมูล", "Weather does not overwrite baseline dates. A calendar adjustment needs a recorded source, separate estimate, deterministic status, and verification level."),
      inheritedContext: text("บริบทจากพื้นที่ระดับบน", "INHERITED CONTEXT"),
      duration: text("ระยะเวลา", "Duration"),
      days: text("วัน", "days"),
    },
    overviewIntelligence: {
      title: text("ภาพรวมข้อมูลเกษตร", "Agriculture Intelligence"),
      subtitle: text("ภาพรวมสถานการณ์เกษตร ปฏิทินเพาะปลูก และโอกาสทางการขาย", "Agriculture situation, planting calendar, and sales opportunity at a glance"),
      scope: text("ขอบเขต", "Scope"),
      presenceBadge: text("การพบพืชที่ยืนยัน {n}/{total}", "Verified crop presence {n}/{total}"),
      updated: text("อัปเดตล่าสุด", "Last updated"),
      kpiCrops: text("ชนิดพืชที่พบ", "Crop types found"),
      kpiCropsSub: text("จากข้อมูลที่ยืนยันแล้ว", "From verified records"),
      kpiArea: text("พื้นที่เพาะปลูกทั้งหมด", "Total cultivated area"),
      kpiAreaSub: text("เฉพาะข้อมูลจริงระดับ Township", "Eligible ACTUAL township records"),
      kpiTownship: text("ครอบคลุมพื้นที่", "Area coverage"),
      kpiTownshipSub: text("จากทั้งหมด {n} Township ในขอบเขต", "Of {n} townships in scope"),
      kpiConfidence: text("ความน่าเชื่อถือข้อมูล", "Data confidence"),
      confidenceHigh: text("สูง", "High"),
      confidenceMedium: text("ปานกลาง", "Medium"),
      confidenceLow: text("ต่ำ", "Low"),
      confidenceNone: text("ไม่มีข้อมูล", "No data"),
      mapTitle: text("แผนที่เกษตรอัจฉริยะ", "Agriculture Intelligence Map"),
      mapSub: text("ความหนาแน่นการปลูกพืช โอกาสทางการขาย และความเสี่ยงในแต่ละพื้นที่", "Crop density, sales opportunity, and risk per area"),
      layerDensity: text("ความหนาแน่นปลูกพืช", "Crop density"),
      layerCropType: text("ชนิดพืชหลัก", "Main crop"),
      layerOpportunity: text("โอกาสทางการขาย", "Sales opportunity"),
      layerRisk: text("ความเสี่ยงสภาพอากาศ", "Weather risk"),
      densityLegend: text("ความหนาแน่นการปลูกพืช", "Crop density"),
      densityHigh: text("ปลูกมาก", "High density"),
      densityMedium: text("ปลูกปานกลาง", "Medium density"),
      densityLow: text("ปลูกน้อย", "Low density"),
      densityNone: text("ไม่มีข้อมูล", "No data"),
      mapNoData: text("ไม่มีข้อมูลพื้นที่ในขอบเขตนี้", "No area data for this scope"),
      mapNoDataHelp: text("ต้องมีข้อมูลการพบพืชระดับ Township หรือสถิติพื้นที่เพาะปลูก", "Requires township crop-presence or area statistics."),
      opportunityEmpty: text("ยังไม่มีข้อมูลโอกาสทางการขาย", "No sales opportunity data yet"),
      opportunityEmptyHelp: text("ระบบจะแสดงโอกาสเมื่อมีข้อมูลเครื่องจักรและกิจกรรมเกษตรประกอบ", "Opportunities appear once machine and farm-activity data are available."),
      riskEmpty: text("ยังไม่มีข้อมูลความเสี่ยงสภาพอากาศ", "No weather risk data yet"),
      riskEmptyHelp: text("แสดงเฉพาะข้อมูลอันตรายย้อนหลังที่บันทึกไว้", "Only recorded historical hazards are shown."),
      hazardHistorical: text("ข้อมูลย้อนหลัง", "Historical"),
      selectedArea: text("ข้อมูลพื้นที่ที่เลือก", "Selected area intelligence"),
      changeArea: text("เปลี่ยนพื้นที่", "Change area"),
      noSelection: text("ยังไม่ได้เลือกพื้นที่", "No area selected"),
      noSelectionHelp: text("คลิกพื้นที่บนแผนที่เพื่อดูรายละเอียด", "Click an area on the map to inspect it."),
      mainCrops: text("พืชหลัก 3 อันดับ", "Top crops"),
      others: text("อื่นๆ", "Others"),
      currentSeason: text("ช่วงเวลาการเพาะปลูกปัจจุบัน", "Current planting period"),
      seasonNoData: text("ยังไม่มีช่วงเวลาที่ยืนยัน", "No verified window"),
      weatherNow: text("สภาพอากาศปัจจุบัน", "Current weather"),
      temperature: text("อุณหภูมิ", "Temperature"),
      humidity: text("ความชื้น", "Humidity"),
      rainfall: text("ฝนสะสม 7 วัน", "Rainfall 7d"),
      opportunityBadge: text("โอกาส", "Opportunity"),
      insightTitle: text("AI Agriculture Insight", "AI Agriculture Insight"),
      insightSub: text("ข้อมูลเชิงลึกจากการวิเคราะห์", "Insights from analysis"),
      insightNoData: text("ยังไม่มีข้อมูลพอสำหรับข้อมูลเชิงลึก", "Not enough data for insight yet"),
      insightNoDataHelp: text("ต้องมีพื้นที่เพาะปลูกหรือข้อมูลปฏิทินก่อน", "Requires area or calendar data first."),
      insightMainArea: text("พื้นที่เพาะปลูกสูงสุด: {area}", "Top cultivated area: {area}"),
      insightMainCrop: text("พืชหลัก: {crop}", "Main crop: {crop}"),
      insightCalendarHelp: text("ข้อมูลช่วงปลูกอ้างอิงจากปฏิทินที่บันทึกไว้ ไม่ใช่สถานะปัจจุบันจากพื้นที่", "Planting windows are reference calendar data, not current field status."),
      insightOpportunity: text("โอกาสทางการขาย: {level}", "Sales opportunity: {level}"),
      rankingTitle: text("พื้นที่เพาะปลูกสูงสุด (TOP 5)", "Top cultivated areas (TOP 5)"),
      rankingSub: text("เฉพาะข้อมูลจริงระดับ Township ปีล่าสุด", "Latest-year ACTUAL township records only"),
      rankingColRank: text("ลำดับ", "Rank"),
      rankingColArea: text("พื้นที่", "Area"),
      rankingColCrop: text("พืชหลัก", "Main crop"),
      rankingColAcres: text("พื้นที่ (acres)", "Area (acres)"),
      rankingColConfidence: text("ความน่าเชื่อถือ", "Confidence"),
      rankingEmpty: text("ยังไม่มีข้อมูลพื้นที่เพาะปลูก", "No cultivated-area data yet"),
      qualityTitle: text("คุณภาพและความครบถ้วนของข้อมูล", "Data quality & completeness"),
      qualitySub: text("ประเมินความสมบูรณ์ของข้อมูลในแต่ละมิติ", "Completeness across data dimensions"),
      qualityPresence: text("ข้อมูลการพบพืช", "Crop presence"),
      qualityArea: text("ข้อมูลพื้นที่เพาะปลูก", "Cultivated area"),
      qualityYield: text("ข้อมูลผลผลิต", "Yield data"),
      qualityCalendar: text("ปฏิทินการเพาะปลูก", "Crop calendar"),
      qualityWeather: text("ข้อมูลสภาพอากาศ", "Weather data"),
      qualityVerification: text("การยืนยันจากพื้นที่", "Field verification"),
      qualityVerified: text("ครบถ้วน", "Verified"),
      qualityPartial: text("บางส่วน", "Partial"),
      qualityMissing: text("ขาด", "Missing"),
      viewGaps: text("ดูช่องว่างข้อมูลทั้งหมด", "View all data gaps"),
      footerNote: text("แผนที่และสถิติอัปเดตจากข้อมูลล่าสุดที่บันทึกไว้", "Map and statistics reflect the latest recorded data."),
      helpAria: text("ความน่าเชื่อถือของข้อมูล", "Data confidence legend"),
      confidenceLegendHigh: text("สูง (ยืนยันแล้ว)", "High (verified)"),
      confidenceLegendMedium: text("ปานกลาง", "Medium"),
      confidenceLegendLow: text("ต่ำ (บางส่วน)", "Low (partial)"),
      confidenceLegendNone: text("ไม่มีข้อมูล", "No data"),
    },
    calendarView: {
      title: text("ปฏิทินการเพาะปลูก (Crop Calendar)", "Crop Calendar"),
      subtitle: text("ปฏิทินเพาะปลูกตามฤดูกาล อ้างอิงข้อมูลภูมิภาคและพื้นที่", "Seasonal planting calendar from regional and local reference data"),
      updated: text("อัปเดตล่าสุด", "Last updated"),
      about: text("เกี่ยวกับข้อมูล", "About the data"),
      download: text("ดาวน์โหลด", "Download"),
      resetFilters: text("รีเซ็ตตัวกรอง", "Reset filters"),
      aboutBody: text("ข้อมูลในหน้านี้เป็นปฏิทินอ้างอิง (baseline) ตามแหล่งสาธารณะและระดับภูมิภาค ยังไม่ใช่สถานะปัจจุบันที่ยืนยันจากพื้นที่ ระยะของพืชแสดงเฉพาะเมื่อมีข้อมูลบันทึกไว้เท่านั้น หากไม่มีข้อมูลจะแสดง 'ไม่มีข้อมูล' และไม่มีการประมาณค่าเพิ่มเติม", "The data on this page is reference-calendar (baseline) data from public and regional sources, not live field-verified status. Crop stages are shown only when recorded; missing data is shown as 'No data' and is never estimated."),
      scope: text("ขอบเขตการวางแผน", "Planning scope"),
      scopeDataLevel: text("ระดับข้อมูล", "Data level"),
      season: text("ปีเพาะปลูก", "Crop year"),
      seasonReference: text("อ้างอิงหลายปี", "Multi-year reference"),
      seasonUnknown: text("ไม่ระบุปีเพาะปลูก", "Crop year unknown"),
      currentSituation: text("สถานการณ์เดือนนี้", "This month's situation"),
      currentSituationHelp: text("อ้างอิงจากช่วงในปฏิทินเท่านั้น · ยังไม่ใช่สถานะปัจจุบันจากพื้นที่", "Derived from calendar reference windows only · not live field status"),
      viewAll: text("ดูรายละเอียดทั้งหมด", "View all details"),
      situationFootnote: text("หมายเหตุ: ข้อมูลนี้เป็นปฏิทินอ้างอิงตามสภาพภูมิภาค ยังไม่ใช่สถานะปัจจุบันจากพื้นที่ (KMM Verification)", "Note: this is a regional reference calendar, not current field status (KMM Verification)."),
      noSituationData: text("ไม่มีข้อมูลช่วงสำหรับขอบเขตนี้", "No calendar windows for this scope"),
      noSituationDataHelp: text("เลือกพื้นที่ที่มีข้อมูลปฏิทินเพื่อดูสถานการณ์รายเดือน", "Select a scope with calendar records to see monthly situation cards."),
      inReferenceWindow: text("ตามช่วงอ้างอิง", "reference window"),
      stageBetween: text("ช่วงกลางฤดู", "Mid-cycle"),
      stageBefore: text("ก่อนช่วง", "Before"),
      stageOutside: text("นอกช่วงหลัก", "Outside main windows"),
      verifiedStage: text("ระยะยืนยันจากพื้นที่", "Field-verified stage"),
      monthsToHarvest: text("อีก", "in"),
      monthsToHarvestSuffix: text("เดือนถึงช่วงเก็บเกี่ยว", "months to harvest window"),
      monthsToTapping: text("เดือนถึงช่วงกรีด", "months to tapping window"),
      inHarvestWindow: text("อยู่ในช่วงเก็บเกี่ยว (อ้างอิง)", "In reference harvest window"),
      inTappingWindow: text("อยู่ในช่วงกรีด (อ้างอิง)", "In reference tapping window"),
      noHarvestWindow: text("ไม่มีข้อมูลช่วงเก็บเกี่ยว", "No harvest window data"),
      typicalWindow: text("ช่วงโดยทั่วไป", "Typical window"),
      timelineTitle: text("ปฏิทินเพาะปลูก 12 เดือน", "12-month crop calendar"),
      timelineHelp: text("แถบแสดงช่วงที่บันทึกในข้อมูลอ้างอิงเท่านั้น หากไม่มีข้อมูลช่วงใดจะไม่สร้างแถบขึ้นมา", "Bars show only recorded reference windows; missing periods are never drawn."),
      mainCropsOnly: text("แสดงเฉพาะพืชหลัก", "Main crops only"),
      export: text("ส่งออก", "Export"),
      legendPrep: text("เตรียมพื้นที่/เพาะกล้า", "Land prep / nursery"),
      legendPlanting: text("เริ่มต้นปลูก", "Planting"),
      legendGrowth: text("เจริญเติบโต", "Growth"),
      legendNearHarvest: text("ใกล้เก็บเกี่ยว", "Near harvest"),
      legendHarvest: text("เก็บเกี่ยว", "Harvest"),
      legendTapping: text("กรีดยาง", "Tapping"),
      legendNoData: text("ไม่มีข้อมูล", "No data"),
      currentMonth: text("เดือนปัจจุบัน", "Current month"),
      cropColumn: text("พืช", "Crop"),
      historicalBadge: text("ข้อมูลย้อนหลัง", "Historical"),
      inheritedBadge: text("สืบทอดจากระดับบน", "Inherited"),
      referenceBadge: text("ข้อมูลอ้างอิง", "Reference"),
      timelineEmpty: text("ไม่มีข้อมูลปฏิทินสำหรับขอบเขตนี้", "No calendar data for this scope"),
      timelineEmptyHelp: text("ไม่มีการประมาณช่วงเดือนจากข้อมูลอ้างอิงอื่น หากต้องการให้แสดงต้องบันทึกข้อมูลปฏิทินสำหรับพื้นที่นี้", "Month windows are not inferred from other references; calendar records for this scope are required."),
      noMainCropsHelp: text("ไม่มีพืชหลักที่ยืนยันในขอบเขตนี้ — แสดงทุกพืชที่มีข้อมูล", "No verified main crops in this scope — showing all crops with data."),
      detailTitle: text("รายละเอียดพืช", "Crop details"),
      detailLocation: text("พื้นที่", "Location"),
      detailSeason: text("ฤดูกาล / ปี", "Season / year"),
      detailStageWindows: text("ช่วงการเพาะปลูก", "Crop schedule"),
      detailDuration: text("รอบการเพาะปลูก", "Crop cycle duration"),
      detailSource: text("แหล่งข้อมูล", "Source"),
      detailSourceYear: text("ปีของแหล่งข้อมูล", "Source year"),
      detailEvidence: text("ระดับหลักฐาน", "Evidence level"),
      detailVerification: text("สถานะการยืนยัน", "Verification status"),
      detailConfidence: text("ความน่าเชื่อถือ", "Confidence"),
      detailYield: text("ผลผลิตต่อพื้นที่", "Local yield"),
      detailYieldNoData: text("ไม่มีข้อมูลผลผลิตในระดับนี้ · ไม่มีการประมาณค่า", "No local yield data · not estimated"),
      detailDeep: text("ดูรายละเอียดเชิงลึก", "View deep details"),
      detailClose: text("ปิด", "Close"),
      detailNoWindow: text("ไม่มีข้อมูลช่วง", "No window data"),
      daysUnit: text("วัน", "days"),
      areaByCrop: text("พื้นที่เพาะปลูกตามพืช", "Cultivated area by crop"),
      areaByCropTownship: text("ข้อมูลจริงระดับ Township", "Township actual records"),
      areaByCropState: text("พื้นที่ปลูกตามข้อมูล CSO 9.12", "Sown area · CSO 9.12"),
      areaTotal: text("รวม", "Total"),
      areaOthers: text("อื่นๆ", "Others"),
      areaNoData: text("ไม่มีข้อมูลพื้นที่ที่เชื่อถือได้ในขอบเขตนี้", "No reliable area data for this scope"),
      areaNoDataHelp: text("แสดงเฉพาะข้อมูลจริงระดับ Township (ACTUAL) หรือพื้นที่ปลูกระดับรัฐ/ภูมิภาคจากแหล่งทางการ", "Shown only from eligible ACTUAL township records or official state/region sown area."),
      relatedAreas: text("พื้นที่ที่เกี่ยวข้อง", "Related areas"),
      relatedAreasCol: text("พื้นที่", "Area"),
      relatedCropCol: text("พืชหลัก", "Main crop"),
      relatedWindowCol: text("ช่วงเพาะปลูก / เก็บเกี่ยว", "Planting / harvest window"),
      relatedNoData: text("ไม่มีข้อมูลรายพื้นที่ในขอบเขตนี้", "No per-area records in this scope"),
      relatedNoDataHelp: text("เลือกขอบเขตระดับ Township หรือ ALL เพื่อดูตารางรายพื้นที่", "Select a township scope or ALL to see the per-area table."),
      relatedHistoricalTag: text("ย้อนหลัง", "Historical"),
      sourcesTitle: text("แหล่งข้อมูล", "Data sources"),
      sourcesYear: text("ปี", "Year"),
      sourcesGeography: text("ระดับพื้นที่", "Geography"),
      sourcesRecords: text("รายการที่อ้างอิง", "linked records"),
      sourcesEmpty: text("ไม่มีแหล่งข้อมูลที่อ้างอิงในขอบเขตนี้", "No linked sources for this scope"),
      badgeVerified: text("ยืนยันแล้ว", "Verified"),
      badgeReference: text("ข้อมูลอ้างอิง", "Reference"),
      badgeUnverified: text("รอการยืนยัน", "Needs verification"),
      badgeNoData: text("ไม่มีข้อมูล", "No data"),
      levelTownship: text("Township", "Township"),
      levelStateRegion: text("รัฐ/ภูมิภาค", "State/Region"),
      levelRegional: text("ระดับภูมิภาค", "Regional"),
      levelNational: text("ระดับประเทศ", "National"),
      levelMixed: text("หลายระดับ", "Mixed"),
      levelNone: text("ไม่ระบุ", "None"),
      downloadAria: text("ดาวน์โหลดข้อมูลปฏิทินเป็น CSV", "Download calendar data as CSV"),
    },
    dataView: {
      title: text("ภาพรวมข้อมูลเกษตร", "Agriculture Data Overview"),
      subtitle: text("สรุปข้อมูลสำคัญของพื้นที่ที่เลือก", "Key agriculture data for the selected scope"),
      metricExplain: text("ดูคำอธิบายตัวชี้วัด", "View indicator descriptions"),
      metricExplainBody: text("ตัวเลขพื้นที่ = ข้อมูลจริง (ACTUAL) ระดับ Township ที่ผ่านเกณฑ์ หรือพื้นที่ปลูกระดับรัฐ/ภูมิภาคจากแหล่งทางการ (CSO 9.12) เท่านั้น แผนและเป้าหมายไม่รวมในตัวเลข KPI แต่แสดงบนการ์ดพืชพร้อมป้ายประเภทข้อมูล ความเชื่อมั่นคำนวณจากระดับการยืนยันของแหล่งข้อมูล (V1–V4)", "Area figures use eligible ACTUAL township records or official state/region sown area (CSO 9.12) only. Plans and targets are excluded from area KPIs but shown on crop cards with their record type. Confidence derives from source verification levels (V1–V4)."),
      scope: text("ขอบเขต", "Scope"),
      season: text("ปีเพาะปลูก", "Crop year"),
      summaryCrops: text("พืชที่พบในพื้นที่", "Crops found in area"),
      summaryCropsSub: text("จากทั้งหมด {n} แหล่งข้อมูล", "From {n} data sources"),
      summaryArea: text("พื้นที่เพาะปลูกที่ยืนยันแล้ว", "Confirmed cultivated area"),
      summaryAreaSub: text("ปีล่าสุด {year}", "Latest year {year}"),
      summaryTownship: text("Township ที่มีข้อมูลสถิติ", "Townships with statistics"),
      summaryTownshipSub: text("จากทั้งหมด {n} Township", "Of {n} townships"),
      townshipUnit: text("แห่ง", ""),
      mainCrop: text("พืชหลัก", "Main crop"),
      summaryConfidence: text("ความสมบูรณ์ของข้อมูล", "Data completeness"),
      confidenceHigh: text("สูง", "High"),
      confidenceMedium: text("ปานกลาง", "Medium"),
      confidenceLow: text("ต่ำ", "Low"),
      confidenceNone: text("ไม่มีข้อมูล", "No data"),
      keyCrops: text("พืชสำคัญในพื้นที่", "Key crops in area"),
      keyCropsSub: text("พืชที่มีการเพาะปลูกในพื้นที่ พร้อมพื้นที่และระดับข้อมูลล่าสุด", "Crops cultivated in the area with latest area and data level"),
      viewAllCrops: text("ดูพืชทั้งหมด ({n} ชนิด)", "View all crops ({n})"),
      badgeActual: text("ข้อมูลจริง", "Actual"),
      badgeTarget: text("เป้าหมาย", "Target"),
      badgePlan: text("แผน", "Plan"),
      badgeEstimated: text("ประมาณการ", "Estimate"),
      badgeReported: text("ที่รายงาน", "Reported"),
      badgeProbable: text("คาดว่าพบ", "Probable"),
      level: text("ระดับ", "Level"),
      latestYear: text("ปีล่าสุด", "Latest year"),
      drawerTitle: text("รายละเอียดพืช", "Crop details"),
      drawerLocation: text("พื้นที่", "Location"),
      drawerArea: text("พื้นที่เพาะปลูก", "Cultivated area"),
      drawerYear: text("ปี", "Year"),
      drawerSeason: text("ฤดูกาล", "Season"),
      drawerRecordType: text("ประเภทข้อมูล", "Record type"),
      drawerPresence: text("สถานะการพบพืช", "Presence"),
      drawerLevel: text("ระดับข้อมูล", "Data level"),
      drawerConfidence: text("ระดับการยืนยัน", "Confidence"),
      drawerImportance: text("ความสำคัญ", "Importance"),
      drawerLocations: text("พื้นที่ที่พบ", "Locations"),
      drawerSources: text("แหล่งข้อมูล", "Sources"),
      drawerClose: text("ปิด", "Close"),
      drawerDeep: text("ดูรายละเอียดเชิงลึก", "View deep details"),
      drawerNoData: text("ไม่มีข้อมูล", "No data"),
      donutTotalLabel: text("รวมพื้นที่", "Total area"),
      donutTitle: text("พื้นที่เพาะปลูก จำแนกตามชนิดพืช", "Cultivated area by crop"),
      donutSub: text("เฉพาะข้อมูลจริง (ACTUAL) ระดับ Township · {unit}", "Eligible ACTUAL township records only · {unit}"),
      donutNoData: text("ไม่มีข้อมูลพื้นที่ที่เชื่อถือได้ในขอบเขตนี้", "No reliable area data for this scope"),
      donutNoDataHelp: text("ต้องมีข้อมูลจริงระดับ Township หรือพื้นที่ปลูกระดับรัฐ/ภูมิภาคจากแหล่งทางการ", "Requires eligible ACTUAL township or official state/region sown-area records."),
      areaOthers: text("อื่นๆ", "Others"),
      rankingTitle: text("เปรียบเทียบพื้นที่เพาะปลูกระหว่างพื้นที่", "Cultivated area by area"),
      rankingSub: text("พื้นที่ที่มีสถิติพื้นที่เพาะปลูก (ACTUAL) ปีล่าสุด", "Areas with latest-year ACTUAL area statistics"),
      rankingNoData: text("ไม่มีข้อมูลเปรียบเทียบพื้นที่", "No per-area comparison data"),
      trendTitle: text("แนวโน้มพื้นที่เพาะปลูก", "Cultivated area trend"),
      trendSub: text("รวมข้อมูลจริง (ACTUAL) รายปี · {unit}", "Eligible ACTUAL records by year · {unit}"),
      trendSingleYear: text("มีข้อมูล 1 ปี ({year}) — ยังไม่พอวาดแนวโน้ม", "Only {year} available — not enough points for a trend"),
      trendNoData: text("ไม่มีข้อมูลแนวโน้มรายปี", "No yearly trend data"),
      qualityTitle: text("คุณภาพและการครอบคลุมข้อมูล", "Data quality and coverage"),
      qualitySub: text("ประเมินความสมบูรณ์ของข้อมูลในพื้นที่", "Completeness of data across pilot townships"),
      qualityPresence: text("การพบพืช", "Crop presence"),
      qualityArea: text("ข้อมูลพื้นที่", "Area data"),
      qualityYield: text("ข้อมูลผลผลิต", "Yield data"),
      qualityCalendar: text("ปฏิทินการเพาะปลูก", "Crop calendar"),
      qualityVerification: text("การยืนยันจากพื้นที่", "Field verification"),
      qualityVerified: text("ครบถ้วน", "Verified"),
      qualityPartial: text("บางส่วน", "Partial"),
      qualityMissing: text("ขาด", "Missing"),
      gapsAlertTitle: text("พบช่องว่างข้อมูล {n} รายการ", "{n} open data gaps"),
      gapsAlertBody: text("ข้อมูลสำคัญยังไม่ครบถ้วน หากมีการยืนยันจากพื้นที่จะช่วยเพิ่มความแม่นยำ", "Key data is incomplete; local field verification would improve accuracy."),
      viewGaps: text("ดูช่องว่างข้อมูล", "View data gaps"),
      sourcesTitle: text("แหล่งข้อมูลหลัก", "Main data sources"),
      sourcesSub: text("แหล่งข้อมูลที่ใช้ในการจัดทำข้อมูล", "Sources used for this page"),
      viewAllSources: text("ดูแหล่งข้อมูลทั้งหมด ({n})", "View all sources ({n})"),
      sourceRecords: text("รายการ", "records"),
      sourcesEmpty: text("ไม่มีแหล่งข้อมูลในขอบเขตนี้", "No sources for this scope"),
      detailTitle: text("บันทึกข้อมูลเกษตรล่าสุด", "Latest agriculture records"),
      detailSub: text("รายการที่พร้อมใช้งานในระบบ (แสดง {n} รายการล่าสุด)", "Available records (showing {n} latest)"),
      viewAllData: text("ดูข้อมูลทั้งหมด ({n})", "View all data ({n})"),
      colLocation: text("พื้นที่", "Area"),
      colCrop: text("ชนิดพืช", "Crop type"),
      colStatus: text("สถานะการพบพืช", "Presence"),
      colLevel: text("ระดับข้อมูล", "Data level"),
      colYearSeason: text("ปี / ฤดูกาล", "Year / Season"),
      colSource: text("แหล่งข้อมูล", "Source"),
      colVerification: text("การยืนยัน", "Verification"),
      searchPlaceholder: text("ค้นหาพื้นที่ / ชนิดพืช / แหล่งข้อมูล…", "Search area, crop, or source…"),
      filterAllTypes: text("ทุกประเภทข้อมูล", "All record types"),
      sortByArea: text("เรียงตามพื้นที่", "Sort by area"),
      sortByYear: text("เรียงตามปี", "Sort by year"),
      sortByLocation: text("เรียงตามพื้นที่", "Sort by location"),
      showMore: text("แสดงเพิ่มเติม", "Show more"),
      showLess: text("แสดงน้อยลง", "Show less"),
      detailEmpty: text("ไม่มีรายการที่ตรงเงื่อนไข", "No records match"),
      detailEmptyHelp: text("ลองค้นหาหรือเปลี่ยนตัวกรอง", "Try a different search or filter."),
      footerNote: text("ข้อมูลในหน้านี้เป็นข้อมูลอ้างอิงจากแหล่งสาธารณะ และข้อมูลยืนยันจากพื้นที่ไม่สมบูรณ์ ควรใช้ประกอบการตัดสินใจเท่านั้น", "This page uses public reference data; field verification is incomplete. Use for decision support only."),
      noCrops: text("ยังไม่มีพืชที่ยืนยันในขอบเขตนี้", "No verified crops for this scope"),
      noCropsHelp: text("ต้องมีข้อมูลการพบพืชระดับ Township ก่อนจึงจะแสดงการ์ดพืช", "Township-level crop presence records are required to show crop cards."),
    },
    verification: {
      title: text("การยืนยันข้อมูลจากพื้นที่ · 2026", "Local Field Verification · 2026"),
      appendOnly: text("ข้อมูลพื้นที่ D1 · เพิ่มรายการเท่านั้น", "LOCAL D1 · APPEND-ONLY"),
      help: text("แสดงข้อมูลอ้างอิงสาธารณะและระดับภูมิภาคก่อน บันทึกเฉพาะสิ่งที่ผู้ให้ข้อมูลในพื้นที่ยืนยัน แก้ไข เพิ่ม หรือระบุว่ายังไม่มีข้อมูลได้ การส่งข้อมูลระดับ V2 จะไม่เลื่อนระดับอัตโนมัติ", "Public and regional baselines appear first. Record only what a local person can VERIFY, CORRECT, ADD, or mark UNKNOWN. V2 submissions are not auto-promoted."),
      verifiedTownships: text("Township ที่ยืนยันแล้ว", "Verified townships"),
      verifiedCrops: text("ชนิดพืชที่ยืนยันแล้ว", "Verified crops"),
      openHighGaps: text("ประเด็นข้อมูลสำคัญที่ยังเปิดอยู่", "Open high gaps"),
      v4v2: text("V4 / V2", "V4 / V2"),
      viewerReadOnly: text("สิทธิ์ผู้ดูเป็นแบบอ่านอย่างเดียว โปรดติดต่อผู้จัดการหรือผู้ดูแลบริษัทเพื่อส่งรายงานจากพื้นที่", "Viewer access is read-only. Ask a manager or company admin to submit a local report."),
      quickVerify: text("ยืนยันข้อมูลแบบรวดเร็ว", "Quick Verify"),
      quickHelp: text("คำตอบหนึ่งครั้งจะสร้างรายงานจากพื้นที่ระดับ V2 หนึ่งรายการ และไม่แก้ไขประวัติจากแหล่งข้อมูลสาธารณะ", "One answer creates one V2 local report. It does not modify public history."),
      selectTownship: text("เลือก Township", "Select township"),
      publicBaseline: text("ข้อมูลอ้างอิงสาธารณะ", "Public baseline"),
      addDetails: text("เพิ่มรายละเอียด", "Add details"),
      baselineEvidence: text("หลักฐานอ้างอิงก่อนบันทึก", "Baseline evidence before entry"),
      selected: text("ที่เลือก", "Selected"),
      noTownship: text("ยังไม่ได้เลือก Township", "No township"),
      noCrop: text("ยังไม่ได้เลือกชนิดพืช", "No crop"),
      latestPublicSourceYear: text("ปีล่าสุดของแหล่งข้อมูลสาธารณะ", "Latest public source year"),
      currentLocalTruth: text("ข้อมูลปัจจุบันจากพื้นที่", "Current local truth"),
      noLocalReport: text("ยังไม่มีรายงานจากพื้นที่", "No local report yet"),
      publicTownshipBaseline: text("ข้อมูลอ้างอิงสาธารณะระดับ Township", "Public township baseline"),
      stateRegionActual: text("ข้อมูลจริงระดับรัฐ/ภูมิภาค", "State / region actual"),
      regionalCalendar: text("ปฏิทินระดับภูมิภาค", "Regional calendar"),
      nationalYieldBaseline: text("ข้อมูลอ้างอิงผลผลิตต่อหน่วยพื้นที่ระดับประเทศ", "National yield baseline"),
      weatherContext: text("ข้อมูลสภาพอากาศประกอบ", "Weather context"),
      historicalHazards: text("เหตุการณ์เสี่ยงย้อนหลัง", "Historical hazards"),
      historicalOnly: text("ข้อมูลย้อนหลังเท่านั้น ไม่อนุมานผลกระทบปัจจุบัน", "Historical only; no current impact inferred."),
      detailedVerification: text("การยืนยันข้อมูลโดยละเอียด", "Detailed verification"),
      fieldsUnknown: text("ทุกช่องจะคงเป็นยังไม่มีข้อมูลยืนยัน/ไม่มีข้อมูล เมื่อผู้ให้ข้อมูลไม่มีหลักฐาน", "All fields remain UNKNOWN/N/A when the respondent has no evidence."),
      openForm: text("เปิดแบบฟอร์ม", "Open form"),
      hideForm: text("ซ่อนแบบฟอร์ม", "Hide form"),
      township: text("Township", "Township"),
      crop: text("ชนิดพืช", "Crop"),
      cropPresence: text("การพบพืช", "Crop presence"),
      importance: text("ความสำคัญ", "Importance"),
      verificationLevel: text("ระดับการยืนยันข้อมูล", "Verification level"),
      estimatedArea: text("พื้นที่ประมาณการ", "Estimated area"),
      areaUnit: text("หน่วยพื้นที่", "Area unit"),
      areaQuality: text("คุณภาพข้อมูลพื้นที่", "Area quality"),
      plantingStart: text("เริ่มปลูก", "Planting start"),
      plantingEnd: text("สิ้นสุดการปลูก", "Planting end"),
      harvestStart: text("เริ่มเก็บเกี่ยว", "Harvest start"),
      harvestEnd: text("สิ้นสุดการเก็บเกี่ยว", "Harvest end"),
      canonicalStageHelp: text("ส่งได้เฉพาะระยะมาตรฐานของชนิดพืชที่เลือก สภาพอากาศและปฏิทินจะไม่กรอกช่องนี้แทน", "Only canonical stages for the selected crop can be submitted; weather and calendar never fill this field."),
      irrigation: text("รูปแบบการให้น้ำ", "Irrigation"),
      mechanization: text("ระดับการใช้เครื่องจักร", "Mechanization"),
      commonMachines: text("เครื่องจักรที่ใช้ทั่วไป", "Common machines"),
      machinesPlaceholder: text("คั่นรายการด้วยจุลภาค; ใช้เป็นข้อมูลสังเกตการณ์เท่านั้น", "Comma-separated; observation only"),
      verificationMethod: text("วิธีการยืนยันข้อมูล", "Verification method"),
      notes: text("หมายเหตุ", "Notes"),
      notesPlaceholder: text("ยังไม่มีข้อมูล / ต้องติดตามเพิ่มเติม", "Unknown / needs follow-up"),
      history: text("ประวัติการยืนยันข้อมูลจากพื้นที่", "Local verification history"),
      historyHelp: text("เก็บข้อมูลจากแหล่งสาธารณะไว้ แม้คำตอบจากพื้นที่จะแตกต่างกัน", "Public source records remain preserved when local answers conflict."),
      conflictPublicPreserved: text("ข้อมูลขัดแย้ง · คงข้อมูลสาธารณะไว้", "Conflict · public preserved"),
      approveAt: text("อนุมัติที่ระดับ", "Approve at"),
      noLocalReports: text("ยังไม่มีรายงานจากพื้นที่ ข้อมูลอ้างอิงสาธารณะยังไม่เปลี่ยนแปลง", "No local reports yet. Public baseline records are unchanged."),
    },
    opportunity: {
      title: text("ข้อมูลวิเคราะห์โอกาสทางการขาย", "Opportunity Intelligence"),
      help: text("เครื่องมือวิเคราะห์โอกาสยังเก็บไว้สำหรับระยะถัดไป รอบข้อมูลเกษตรนี้จึงยังไม่แนะนำเครื่องจักรและยังไม่เปิดใช้ตัวแปรคะแนนใหม่", "The opportunity engine remains available for a later phase, but Agriculture Data-first does not promote machine recommendations or activate new scoring inputs."),
      model: text("รุ่นแบบจำลอง", "Model"),
      status: text("สถานะ", "Status"),
      records: text("รายการ", "Records"),
      paused: text("หยุดไว้ชั่วคราว", "Paused"),
      held: text("รอเปิดใช้", "held"),
      defaultWeights: text("ค่าน้ำหนักเริ่มต้น v0.1", "Default v0.1 weights"),
      ranking: text("การจัดลำดับโอกาส", "Opportunity Ranking"),
      rankingHelp: text("รอจนกว่าจะมีระยะพืชปัจจุบัน ความเป็นเจ้าของของลูกค้า/ผู้รับเหมา และข้อมูลยืนยันจากพื้นที่", "Held until current crop stage, ownership, and local verification are available"),
      pausedTitle: text("การวิเคราะห์โอกาสหยุดไว้ชั่วคราว", "Opportunity Intelligence paused"),
      pausedMessage: text("จะเปิดใช้การวิเคราะห์โอกาสเมื่อมีระยะพืชปัจจุบัน ข้อมูลความเป็นเจ้าของของลูกค้า/เครื่องจักร และข้อมูลยืนยันจากพื้นที่แล้ว", "Opportunity Intelligence will be enabled after current crop stage, customer/machine ownership, and local verification are available."),
    },
  };
}

export function agricultureGeographyLabel(value: string | null | undefined, language: Language) {
  if (language !== "th") return value ?? "Geography N/A";
  return ({
    ALL: "ทุกระดับพื้นที่",
    TOWNSHIP: "Township (เขตการปกครอง)",
    STATE_REGION: "รัฐ/ภูมิภาค",
    REGIONAL: "ระดับภูมิภาค",
    NATIONAL: "ระดับประเทศ",
    NATIONAL_REGIONAL: "ระดับประเทศ/ภูมิภาค",
  } as Record<string, string>)[value ?? ""] ?? value ?? "ไม่ระบุระดับพื้นที่";
}

export function agricultureSourceGeographyLabel(value: string | null | undefined, language: Language) {
  if (language !== "th") return value ?? "Geography N/A";
  return agricultureGeographyLabel(value, language);
}

export function agriculturePresenceLabel(value: string | null | undefined, language: Language) {
  if (language !== "th") return value ?? "Unknown";
  return ({
    CONFIRMED_PRESENT: "ยืนยันว่าพบพืช",
    PROBABLE: "คาดว่าพบพืช",
    HISTORICAL: "พบในข้อมูลย้อนหลัง",
    UNKNOWN: "ยังไม่มีข้อมูลยืนยัน",
    CONFIRMED_ABSENT: "ยืนยันว่าไม่พบพืช",
  } as Record<string, string>)[value ?? ""] ?? value ?? "ยังไม่มีข้อมูลยืนยัน";
}

export function agricultureAnswerLabel(value: string | null | undefined, language: Language) {
  if (language !== "th") return value ?? "UNKNOWN";
  return ({ YES: "พบ", NO: "ไม่พบ", UNKNOWN: "ยังไม่มีข้อมูลยืนยัน" } as Record<string, string>)[value ?? ""] ?? value ?? "ยังไม่มีข้อมูลยืนยัน";
}

export function agricultureVerificationLevelLabel(value: string | null | undefined, language: Language) {
  if (language !== "th") return value ?? "UNKNOWN";
  const label = ({
    V0: "ยังไม่มีข้อมูล",
    V1: "ข้อมูลอ้างอิงจากแหล่งสาธารณะ",
    V2: "ข้อมูลรายงานจากพื้นที่",
    V3: "ตรวจสอบยืนยันจากหลายแหล่ง",
    V4: "ข้อมูลปัจจุบันที่ยืนยันแล้ว",
    UNKNOWN: "ยังไม่มีข้อมูลยืนยัน",
  } as Record<string, string>)[value ?? ""] ?? "ยังไม่มีข้อมูลยืนยัน";
  return value ? `${value} · ${label}` : label;
}

export function agricultureRecordTypeLabel(value: string | null | undefined, language: Language) {
  if (language !== "th") return value ?? "UNKNOWN";
  return ({
    ACTUAL: "ข้อมูลจริง",
    ACTUAL_OFFICIAL: "ข้อมูลจริงจากแหล่งทางการ",
    TARGET: "เป้าหมาย",
    PLAN: "แผน",
    ESTIMATE: "ประมาณการ",
    REPORTED: "ข้อมูลที่รายงาน",
  } as Record<string, string>)[value ?? ""] ?? value ?? "ยังไม่มีข้อมูลยืนยัน";
}

export function agricultureVerificationStatusLabel(value: string | null | undefined, language: Language) {
  if (language !== "th") return value ?? "UNKNOWN";
  return ({ PENDING: "รอตรวจสอบ", APPROVED: "อนุมัติแล้ว", REJECTED: "ไม่อนุมัติ", VERIFIED: "ยืนยันแล้ว", UNKNOWN: "ยังไม่มีข้อมูลยืนยัน" } as Record<string, string>)[value ?? ""] ?? value ?? "ยังไม่มีข้อมูลยืนยัน";
}

export function agricultureStageLabel(value: string | null | undefined, language: Language, fallback?: string | null) {
  if (language !== "th") return fallback ?? value ?? "Unknown";
  return ({
    LAND_PREPARATION: "เตรียมพื้นที่",
    NURSERY_SEED_PREP: "เตรียมแปลงเพาะ/เมล็ดพันธุ์",
    SOWING: "หว่านเมล็ด",
    PLANTING: "ปลูก",
    TRANSPLANTING_DIRECT_SEEDING: "ย้ายกล้า/หว่านโดยตรง",
    TILLERING: "แตกกอ",
    PANICLE_INITIATION: "เริ่มสร้างรวง",
    FLOWERING: "ออกดอก",
    GRAIN_FILLING: "สร้างเมล็ด",
    POD_DEVELOPMENT: "สร้างฝัก",
    CAPSULE_DEVELOPMENT: "สร้างฝักเมล็ด",
    PEGGING: "ลงเข็ม",
    EMERGENCE: "เริ่มงอก",
    VEGETATIVE: "เจริญเติบโตทางลำต้น",
    TASSELING: "ออกไหม",
    SILKING: "สร้างไหม",
    MATURITY: "แก่เต็มที่",
    HARVEST: "เก็บเกี่ยว",
    POST_HARVEST: "หลังเก็บเกี่ยว",
    DRYING: "ตากแห้ง",
    IMMATURE_GROWTH: "เติบโตระยะยังไม่ให้ผลผลิต",
    MATURE_PLANTATION: "แปลงโตเต็มที่",
    TAPPING: "กรีดยาง",
    REDUCED_TAPPING: "ลดการกรีดยาง",
    MAINTENANCE: "บำรุงรักษา",
    REPLANTING: "ปลูกทดแทน",
  } as Record<string, string>)[value ?? ""] ?? fallback ?? value ?? "ยังไม่มีข้อมูลยืนยัน";
}

export function agricultureCropName(value: string | null | undefined, code: string | null | undefined, language: Language) {
  if (language !== "th") return value ?? "Unknown crop";
  return ({
    RICE: "ข้าว",
    MAIZE: "ข้าวโพด",
    RUBBER: "ยางพารา",
    GREEN_GRAM: "ถั่วเขียว",
    BLACK_GRAM: "ถั่วดำ",
    GROUNDNUT: "ถั่วลิสง",
    SESAME: "งา",
    SUNFLOWER: "ทานตะวัน",
    CHICKPEA: "ถั่วลูกไก่",
    COTTON: "ฝ้าย",
    JUTE_KENAF: "ปอ/ปอกระเจา",
    VEGETABLES: "ผัก",
    FRUITS: "ผลไม้",
    SUGARCANE: "อ้อย",
  } as Record<string, string>)[code ?? ""] ?? value ?? "ไม่ระบุชนิดพืช";
}

export function agricultureMetricLabel(value: AgricultureTrendMetric, language: Language) {
  if (value === "HARVESTED_AREA") return localizedText(language, "พื้นที่เก็บเกี่ยวแล้ว", "Harvested Area");
  if (value === "PRODUCTION") return localizedText(language, "ผลผลิต", "Production");
  return localizedText(language, "พื้นที่ปลูก", "Sown Area");
}

export function agricultureSeasonLabel(value: string | null | undefined, language: Language) {
  if (language !== "th") return value ?? "Season N/A";
  return ({
    RAIN_FED: "นาน้ำฝน",
    "RAIN-FED": "นาน้ำฝน",
    Rainfed: "นาน้ำฝน",
    "Rain-fed": "นาน้ำฝน",
    WINTER: "ฤดูหนาว",
    Winter: "ฤดูหนาว",
    SUMMER: "ฤดูร้อน",
    Summer: "ฤดูร้อน",
    MAIN_MONSOON: "ฤดูฝนหลัก",
    "Main Monsoon": "ฤดูฝนหลัก",
    POST_MONSOON: "หลังฤดูฝน",
    "Post-Monsoon": "หลังฤดูฝน",
    PERENNIAL: "พืชยืนต้น",
    Perennial: "พืชยืนต้น",
  } as Record<string, string>)[value ?? ""] ?? value ?? "ไม่ระบุฤดูกาล";
}

export function agricultureHazardLabel(value: string | null | undefined, language: Language) {
  if (language !== "th") return value ?? "Unknown hazard";
  const normalized = value?.trim().toUpperCase().replace(/[\s-]+/g, "_");
  return ({
    FLOOD: "น้ำท่วม",
    DROUGHT: "ภัยแล้ง",
    STORM: "พายุ",
    CYCLONE: "พายุไซโคลน",
    HEAT: "คลื่นความร้อน",
    FIRE: "ไฟไหม้",
    PEST: "ศัตรูพืช",
    DISEASE: "โรคพืช",
  } as Record<string, string>)[normalized ?? ""] ?? value ?? "ไม่ระบุเหตุการณ์เสี่ยง";
}

export function agricultureWeatherVariableLabel(value: string | null | undefined, language: Language) {
  if (language !== "th") return value ?? "Unknown weather variable";
  const normalized = value?.trim().toUpperCase().replace(/[\s-]+/g, "_");
  return ({
    RAIN: "ฝน",
    RAINFALL: "ปริมาณฝน",
    RAINFALL_7D: "ปริมาณฝน 7 วัน",
    TEMPERATURE: "อุณหภูมิ",
    HUMIDITY: "ความชื้น",
    WIND: "ลม",
    SOIL_MOISTURE: "ความชื้นในดิน",
    FLOOD: "น้ำท่วม",
    DROUGHT: "ภัยแล้ง",
  } as Record<string, string>)[normalized ?? ""] ?? value ?? "ไม่ระบุตัวแปรสภาพอากาศ";
}

export function agricultureWeatherStateLabel(value: string | null | undefined, language: Language) {
  if (language !== "th") return value ?? "UNKNOWN";
  const normalized = value?.trim().toUpperCase().replace(/[\s-]+/g, "_");
  return ({
    HIGH: "สูง",
    MEDIUM: "ปานกลาง",
    LOW: "ต่ำ",
    CRITICAL: "วิกฤต",
    WARNING: "เฝ้าระวัง",
    NORMAL: "ปกติ",
    UNKNOWN: "ยังไม่มีข้อมูลยืนยัน",
  } as Record<string, string>)[normalized ?? ""] ?? value ?? "ยังไม่มีข้อมูลยืนยัน";
}

export function agricultureCalendarPrecisionLabel(value: string | null | undefined, language: Language) {
  if (language !== "th") return value?.toLowerCase().replaceAll("_", " ") ?? "precision N/A";
  return ({ MONTH: "รายเดือน", EARLY_MONTH: "ต้นเดือน", MID_MONTH: "กลางเดือน", LATE_MONTH: "ปลายเดือน", MONTH_RANGE: "ช่วงเดือน", SEASON_ONLY: "ระบุเฉพาะฤดูกาล" } as Record<string, string>)[value ?? ""] ?? "ไม่ระบุความละเอียด";
}

export function agricultureImportanceLabel(value: string | null | undefined, language: Language) {
  if (language !== "th") return value ?? "UNKNOWN";
  return ({ MAJOR: "หลัก", SECONDARY: "รอง", MINOR: "เล็กน้อย", UNKNOWN: "ยังไม่มีข้อมูลยืนยัน" } as Record<string, string>)[value ?? ""] ?? value ?? "ยังไม่มีข้อมูลยืนยัน";
}

export function agricultureAreaQualityLabel(value: string | null | undefined, language: Language) {
  if (language !== "th") return value ?? "UNKNOWN";
  return ({ KNOWN: "ทราบค่า", APPROXIMATE: "โดยประมาณ", UNKNOWN: "ยังไม่มีข้อมูลยืนยัน" } as Record<string, string>)[value ?? ""] ?? value ?? "ยังไม่มีข้อมูลยืนยัน";
}

export function agricultureIrrigationLabel(value: string | null | undefined, language: Language) {
  if (language !== "th") return value ?? "UNKNOWN";
  return ({ RAIN_FED: "อาศัยน้ำฝน", IRRIGATED: "มีระบบให้น้ำ", MIXED: "ผสมน้ำฝนและระบบให้น้ำ", UNKNOWN: "ยังไม่มีข้อมูลยืนยัน" } as Record<string, string>)[value ?? ""] ?? value ?? "ยังไม่มีข้อมูลยืนยัน";
}

export function agricultureMechanizationLabel(value: string | null | undefined, language: Language) {
  if (language !== "th") return value ?? "UNKNOWN";
  return ({ LOW: "ต่ำ", MEDIUM: "ปานกลาง", HIGH: "สูง", UNKNOWN: "ยังไม่มีข้อมูลยืนยัน" } as Record<string, string>)[value ?? ""] ?? value ?? "ยังไม่มีข้อมูลยืนยัน";
}

export function agricultureVerificationMethodLabel(value: string | null | undefined, language: Language) {
  if (language !== "th") return value ?? "OTHER";
  return ({ FIELD_VISIT: "ลงพื้นที่ตรวจสอบ", BRANCH_REPORT: "รายงานจากสาขา", SALESPERSON_REPORT: "รายงานจากพนักงานขาย", CUSTOMER_REPORT: "รายงานจากลูกค้า", MANAGER_CONFIRMATION: "ผู้จัดการยืนยัน", OTHER: "อื่น ๆ" } as Record<string, string>)[value ?? ""] ?? value ?? "อื่น ๆ";
}

export function agriculturePriorityLabel(value: string | null | undefined, language: Language) {
  if (language !== "th") return value ?? "LOW";
  return ({ HIGH: "สูง", MEDIUM: "ปานกลาง", LOW: "ต่ำ" } as Record<string, string>)[value ?? ""] ?? value ?? "ต่ำ";
}

export function agricultureGapTypeLabel(value: string | null | undefined, language: Language) {
  if (language !== "th") return value ?? "UNKNOWN";
  return ({ CROP_PRESENCE: "การพบพืช", CULTIVATED_AREA: "พื้นที่เพาะปลูก", PRODUCTION: "ผลผลิต", YIELD: "ผลผลิตต่อหน่วยพื้นที่", CALENDAR: "ปฏิทินการเพาะปลูก", CURRENT_STAGE: "ระยะพืชปัจจุบัน", VARIETY: "พันธุ์พืช", COORDINATES: "พิกัดพื้นที่", WEATHER_MAPPING: "การเชื่อมโยงสภาพอากาศ" } as Record<string, string>)[value ?? ""] ?? value ?? "ยังไม่มีข้อมูลยืนยัน";
}

export function agricultureContextStatusLabel(value: string | null | undefined, language: Language) {
  if (language !== "th") return value ?? "REGIONAL CONTEXT";
  return value === "HISTORICAL" ? "ข้อมูลย้อนหลัง" : "บริบทระดับภูมิภาค";
}

export function agricultureDataStatusLabel(value: string | null | undefined, language: Language) {
  if (language !== "th") return value ?? "Loading";
  return ({ available: "มีข้อมูล", partial: "มีข้อมูลบางส่วน", needs_verification: "รอตรวจสอบ", unavailable: "ไม่มีข้อมูล" } as Record<string, string>)[value ?? ""] ?? value ?? "กำลังโหลด";
}

export function agricultureWeatherAvailabilityLabel(value: string | null | undefined, language: Language) {
  if (language !== "th") return value ?? "UNAVAILABLE";
  return ({ LIVE: "สด", CACHED: "จากแคช", STALE: "ข้อมูลเก่า", UNAVAILABLE: "ไม่มีข้อมูล" } as Record<string, string>)[value ?? ""] ?? value ?? "ไม่มีข้อมูล";
}

export function agricultureValueQualifierLabel(value: string | null | undefined, language: Language) {
  if (language !== "th") return value ?? "UNKNOWN";
  return ({ EXACT: "ค่าตรง", APPROXIMATE: "โดยประมาณ", MORE_THAN: "มากกว่า", LESS_THAN: "น้อยกว่า", RANGE: "เป็นช่วง", UNKNOWN: "ยังไม่มีข้อมูลยืนยัน" } as Record<string, string>)[value ?? ""] ?? value ?? "ยังไม่มีข้อมูลยืนยัน";
}
